### ISSUE TITLE
inconsistent install behavior

### ISSUE THREAD

**Issue by jdc0589** [appbaseio/dejaVu#10]
I've got weird behavior installing dejavu as an ES plugin, and running it stand-alone. This is all using chrome.

**as a plugin:**
1. works OK locally
2. ~~404s on main.min.js in another environment when loading splash page~~

**built + run locally (npm install, bower install, gulp watch):**
1. splash page loads. bombs out on something about chrome localstorage when I try to connect. `chrome.storage` is undefined (in chrome). ` "url" == e.name ? chrome.storage.local.set({`

Am I missing something?

**Comment by farhan687** [comment]
`chrome.storage` is specific for **chrome-extension** and we have used that in only chrome-extension branch. By mistake if I used it some other branch else please let me know.

And to detect the error, can you look to index.html and change the file to `main.js` instead of main.min.js. then run the gulp watch and copy the error message over here.

**Comment by jdc0589** [comment]
@farhan687 that chrome extension issue was either on dev, or the most recent tagged release

**Comment by farhan687** [comment]
Hi @jdc0589 
I checked the dev, master and chrome-extension branch, it is working fine for me, didn't find any error in console.

and yes 
built + run locally (npm install, bower install, gulp watch) is the correct steps, you are not missing anything.
just make sure you are not on chrome-extension branch.

**Comment by siddharthlatest** [comment]
@jdc0589 I have added a ``developing`` section https://github.com/appbaseio/dejaVu/blob/dev/README.md#developing.

Your steps for running locally are correct, but it seems you are either using the ``chrome-extension`` branch or the releases (which are specific to the chrome app atm). As you noticed, the localStorage API works differently for a chrome extension and hence the failures when running it in the browser environment.

The recommended branch to build locally is ``master``. Thanks for pointing this :+1:.
