### ISSUE TITLE
UI/UX polishes

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/dejaVu#100]
- [x] The array field should be in a single line (figure out a way with ellipsis perhaps)
- [x] Change the UI for checkboxes and row numbers (like airtable)
- [x] Row height should be fixed (allow 20 rows to be visible on a normal desktop screen)
- [x] Ellipsis on the text fields only (optimize array for showing maximum number of items)
- [x] Geo points in a single row
- [x] Use new colors
- [x] Update colors for labels and lat and lon (light grey)
- [x] Overflow (scroll x) remove outer scroll (shows up on chrome linux)
- [x] Add data button should be removed (add new row button would substitute this)
- [x] Use icons instead of label texts (similar to importer) for datatypes. Clicking on these will show mapping details
- [x] Have a single cell layout (remove cell within a cell)
- [x] Let the input fields cover the entire cell (remove paddings)
- [x] Row numbers UI changes - color changes - (like airtable)
- [x] Add row button padding
- [x] Keep the first column visible when scrolling horizontally
- [x] Keep the add row button visible when scrolling vertically
- [x] Change add record button text to 'Add Data'
- [x] Disconnect button color should be changed since it's a negative action
- [x] Subtle colors for filters
- [x] Update all icons with new color set
- [x] Improve UI/UX flow for arrays and object creation in new column

**Comment by siddharthlatest** [comment]
@divyanshu013 We need to think more about the color scheme here, it is hard to tell which of the two tabs is actually selected here.

![](https://i.imgur.com/UGFoSUU.png)

I would have guessed "Queries", but it is actually "Types" that is selected.

**Comment by divyanshu013** [comment]
I'll try something for the tabs
