### ISSUE TITLE
CSV export not working with filters applied

### ISSUE THREAD

**Issue by jonassvalin** [appbaseio/dejaVu#104]
Docker Image, Latest

JSON/CSV exports seem to work correctly for unfiltered data, but when applying a filter it no longer works correctly and only returns the first 10 results. This can also be seen under "Network" in the browser, it is not scrolling through using the scroll API, but only performing one request.

**Comment by siddharthlatest** [comment]
@jonassvalin thanks for the report. I am able to replicate the issue, this happens across all the distributions.
