### ISSUE TITLE
Running Dejavu on a WebServer

### ISSUE THREAD

**Issue by mmacny** [appbaseio/dejaVu#105]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Running Dejavu on an Ubuntu Server w/ Docker Image

#### What is the version of Dejavu that you are using?
1.0

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
- Running elasticsearch on AWS. 
- Permitted inbound IP of webserver.
- Deploy Dejavu on webserver through Docker
- Unable to connect to ES because of CORS config.

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.
Trying to find a way to deploy the webapp so that I can use it for the rest of my team to browse our ES data.

**Comment by siddharthlatest** [comment]
@mmacny This is a good point. AWS's Elasticsearch service doesn't allow you to configure the cluster (or domain in their terminology) with the elasticsearch.yml which is where you can set the CORS permissions to allow the domain:port where dejavu is running.

An alternative that can work in this case is you setting up an API gateway endpoint which allows CORS for the dejavu's domain:port which then forwards the request to your AWS ES service.

I would be curious if this works well and would want to include a small write up for future users explaining how to set it up.

**Comment by siddharthlatest** [comment]
@mmacny This should work now out of the box, try the `appbaseio/dejavu:1.1` or latest tag.

**Comment by mmacny** [comment]
@siddharthlatest You guys are awesome. I'll give it a try this week.
