### ISSUE TITLE
How to use dejavu for local?

### ISSUE THREAD

**Issue by amigo1205** [appbaseio/dejaVu#106]
Hi 

I heard that there is an excellent tool to manage elasticsearch and yeah just dejavu.
So I've installed elasticsearch 5.6 (the latest version) and dejavu (dev branch) on my local.

The thing is I have no clue how to browse my local elasticsearch dataset using dejavu.
Is there any tutorial or guide to lead us? Please let me know if yes.

I tried to do this several times before but I've failed at that times.

![image](https://user-images.githubusercontent.com/29459701/30920850-922bc64e-a3d7-11e7-84b2-dc68bc96fe5b.png)

As  you see the above image I can't continue to use dejavu. What can I do to resolve this and what is the reason? 
Very URGENT. 
Anybody help me. 
Thanks.

**Comment by siddharthlatest** [comment]
@amigo1205 It seems you haven't enabled CORS config in your local Elasticsearch cluster. You will need to add the following lines in your elasticsearch.yml file:

```
http.port: 9200
http.cors.allow-origin: "http://localhost:1358"
http.cors.enabled: true
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.allow-credentials: true
```

Reference: https://github.com/appbaseio/dejavu#cors

**Comment by amigo1205** [comment]
Thanks for your reply.

And I already added them in my elasticsearch config.

![image](https://user-images.githubusercontent.com/29459701/30928517-6c6c2cfc-a3ee-11e7-97ba-32a06a1ee4dd.png)

As you see, everything is perfect.

Hint : I tried with dejavu docker at the moment and it worked. :)
          But doesn't work when I pull the git source code and build on my local.

**Comment by siddharthlatest** [comment]
@amigo1205 You shouldn't be seeing a CORS issue with this config. Also dev is bleeding edge and has undergone some good amount of changes since the last release, so it is possible something else might be the issue there although I am able to use it fine with a local ES cluster.

**Comment by amigo1205** [comment]
Are there any differences between the git repo and docker project?

**Comment by divyanshu013** [comment]
Hi @amigo1205 can you pull in the latest commit and give it a test after running <s>`bower install`</s> `yarn` in the *dev* branch. It should resolve the error you were seeing. Let us know

**Comment by amigo1205** [comment]
Yeah thanks.
The latest version of dejavu works now.

**Comment by Danelicious** [comment]
I have problems run dejavu on my local machine as well. My ES settings look like this:

`http.port: 9200
http.cors.allow-orgin: "*"
http.cors.enabled: true
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.allow-credentials: true`

I can't connect anywhere, neither with the Chrome extension, nor with the docker image. Is there anything I am missing? I already have an index in ES. Afterwards I open http://localhost:1358/ or alternatively the Chrome extension. What is the next step? Or should I be able to connect already? I still get the message: 

> To make sure you have enabled CORS settings for your ElasticSearch instance, add the following lines in the ES configuration file: 
http.port: 9200
http.cors.allow-origin: http://localhost:1358,http://127.0.0.1:1358
http.cors.enabled: true
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.allow-credentials: true

I tried to change the "http.cors.allow-origin" to the value of the above error message, but also didn't work.
