### ISSUE TITLE
Not able to connect to AWS ES

### ISSUE THREAD

**Issue by vanditamathur** [appbaseio/dejaVu#108]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

Within appbase.io (https://opensource.appbase.io/dejavu/live)

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

With the online link, I get the following error -
"Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://opensource.appbase.io' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."

For the online usage of dejavu, the issue seems to be this -
The response that comes to the pre-flight request has "Access-Control-Allow-Origin" header set to *
However, it seems that if you are making the request using the "withCredentials" flag set to true, then a wildcard response is not acceptable.
Since AWS ES seems to be sending the wildcard in response, this would mean that you should not make the request with the "withCredentials" flag set to true. It should be set to false.

**Comment by siddharthlatest** [comment]
Thanks @vanditamathur, I am able to replicate a solve where your suggested solution works. We should be releasing the fix to this in the next version. This should also solve #105 and the previously closed #79.
