### ISSUE TITLE
feature: optionally expand the width of the ID column

### ISSUE THREAD

**Issue by jdc0589** [appbaseio/dejaVu#11]
If your type + id strings are longer than about 20 characters, it gets truncated in the id column (which is expected, to an extent). It would be nice if there was a way to expand the width of the ID column to make a larger portion of IDs visible. This would make it a lot easier to browse data; which is pretty difficult right now.

Additionally, the `{...}` show json button takes up a lot of screen real estate.

**Comment by siddharthlatest** [comment]
There are a couple of ways to make the experience better here:

  
![id_tooltip](https://cloud.githubusercontent.com/assets/630042/14122265/a873373e-f618-11e5-984a-841f36586a97.png)
1. Hovering over id part of the text displays the entire id in a tooltip.
2. Starting v0.4.3, single-clicking on any cell in the type/id column copies the cell value to the clipboard.

This doesn't entirely replace the need for expanding the column to see longish ids clearly. If / when we're to support that, we also should support general column resizing. While it's not trivial from the UI standpoint, we would like to support it even if it takes a while. I am going to create a new issue which asks for column resizing support.

As for the ``{...}``, it takes ~10% of the column width space. It's a handy way to copy and use the document data as a JSON, we don't intend to change anything there unless there's a good reason to.
