### ISSUE TITLE
websocket connection failure

### ISSUE THREAD

**Issue by jdc0589** [appbaseio/dejaVu#12]
dejaVu installed as an ES plugin.

`WebSocket connection to 'ws://xxxx:9200/meta' failed: Error during WebSocket handshake: Unexpected response code: 200`

Is there an extra plugin dependency for the live-reload to work? Or is this a feature only supported within appbase?

**Comment by siddharthlatest** [comment]
Live-reload only works with appbase. Other Elasticsearch providers do not support realtime (as of now).

**Comment by jdc0589** [comment]
What I suspected, just couldn't find mention of it anywhere. Thanks.

**Comment by zajacm** [comment]
I've spotted the same issue on my local. 
Running Elasticsearch with:
```
docker run --name es -d -p 9200:9200 -d elasticsearch:5 -E http.port=9200 -E http.cors.allow-origin="http://localhost:1358" -E http.cors.enabled=true -E http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -E http.cors.allow-credentials=true
```
and in browser:
![image](https://user-images.githubusercontent.com/5364505/30160492-eb950e9a-93cc-11e7-8373-4a8b6ca16927.png)

what can be a problem?

**Comment by siddharthlatest** [comment]
@zajacm This shouldn't have any material effects. The reason this happens is that dejavu assumes that you are connecting to appbase hosted Elasticsearch and tries to create a live connection via websocket.

**Comment by zajacm** [comment]
Yeah, dejavu works fine, just wanted to get this nice feature. Is there any way to get it working?

**Comment by siddharthlatest** [comment]
@zajacm The Elasticsearch backend needs to support a realtime mode, currently, this is available only on hosted appbase.io. We're working on a docker image of appbase.io that can run against a generic ES cluster to have this available more broadly.

**Comment by zajacm** [comment]
Ok, it's clear now. Thanks!
