### ISSUE TITLE
List indices instead of requiring appname

### ISSUE THREAD

**Issue by cweiske** [appbaseio/dejaVu#120]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
chrome extension

#### What is the version of Dejavu that you are using?
1.1.1

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
I tried to use dejavu as elasticsearch head alternative, but - in contrast to head - does not seem to support multiple indices.

It should be enough to  put `http://localhost:4200` into the cluster URL field, and dejavu should simply show all of the indices that are available.

**Comment by siddharthlatest** [comment]
@cweiske You're right, currently only a single index is supported.

**Comment by siddharthlatest** [comment]
We can implement this in the next release.
