### ISSUE TITLE
Unable to read an app with an empty mappings object

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejaVu#123]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

Hosted web app

#### What is the version of Dejavu that you are using?

1.2.0

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

Dejavu throws a `Uncaught TypeError: Cannot read property 'mappings' of undefined` when trying to connect to an index which has an empty `mappings` object.

##### If your issue deals with accessing Elasticsearch cluster, share the necessary steps to replicate the behavior (the configuration.yml settings, where your ES cluster is hosted, any relevant logs).

Create an index with no mapping templates applied to it.

**Comment by divyanshu013** [comment]
Unable to replicate the issue on local ES index
