### ISSUE TITLE
UI Issue: Unable to close modal

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejaVu#124]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

Hosted web app

#### What is the version of Dejavu that you are using?

1.2.0

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

![](https://i.imgur.com/Kq8mYWb.png)

When a user sees an authentication error modal, the close button click doesn't work.

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.

No console errors or logs appear.

**Comment by ayushjn20** [comment]
I would like to contribute and fix this bug.

**Comment by frytyler** [comment]
I'll try and see if I can find out what's happening here and submit a PR.

**Comment by frytyler** [comment]
Sorry I just followed you build locally instructions and I'm up and running however I'm at the log in screen with app name and url. Is there local credentials for this? I've never used you app before so I'm unfamiliar with what's needed. 

![screenshot 2017-10-23 08 26 10](https://user-images.githubusercontent.com/1922965/31888943-f252215a-b7cb-11e7-918a-0d9a09b37a7a.png)

**Comment by siddharthlatest** [comment]
@frytyler You can generate your appname and URL from https://dashboard.appbase.io, or you can set up a local Elasticsearch cluster. Unless you are already familiar with Elasticsearch, I recommend the first approach.

**Comment by frytyler** [comment]
@siddharthlatest Sorry to ask another question but how was this reproduced? if you auth through the api token / url how are you ever unauthed?

**Comment by siddharthlatest** [comment]
@frytyler There are two kinds of credentials, one is for read and one is for read + write. This error occurs when using a read credential and trying to perform an edit operation, like updating a cell's value (which should only have been possible with a write credential).

**Comment by divyanshu013** [comment]
Resolved in #128
