### ISSUE TITLE
Display of array fields fails on single entry fields

### ISSUE THREAD

**Issue by hb020** [appbaseio/dejaVu#126]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

appbase.io

#### What is the version of Dejavu that you are using?

latest as of today

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

subject: a column that has an array of strings, with column description in dejavu
```
{
 "type": "text",
 "fields": {
  "keyword": {
   "type": "keyword",
   "ignore_above": 256
  }
 }
}
```
The column has "string" type in elasticsearch. The column was created in elasticsearch, not via dejavu.

When the field's content is  
```
[
 "line 1",
 "line 2"
]
```
, the display in dejavu data view, in Viewing mode, will be `[...]`, with a popup showing the values. That is acceptable.

However, when the field is like 
```
[
 "line 1"
]
```
, one sees the text "Enter or select values", and no possibility to see the value.

By the way, once you edit the field to hold more values, via the 'editing' button above, the screen is not updated.

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.

![screen shot 2017-10-23 at 15 27 30](https://user-images.githubusercontent.com/12572422/31891459-c6c59ec8-b806-11e7-8d7e-b6e32126cc0d.png)

**Comment by divyanshu013** [comment]
Hi @hb020 thanks for letting us know. Can you pull in the latest changes on `dev` branch and give it a try? I think it should solve the issue you were seeing.

**Comment by hb020** [comment]
pulled it, but can't get it to compile.
```
>npm install
npm WARN engine request@2.83.0: wanted: {"node":">= 4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine har-validator@5.0.3: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine form-data@2.3.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine sntp@2.0.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine hoek@4.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
\
> node-sass@4.5.3 install /home/hboot/dejavu/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

/home/hboot/dejavu/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/hboot/dejavu/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hboot/dejavu/npm-debug.log
```
on Ubuntu 16.04 LTS
I'm no node.js expert, so I'm lost at how to solve this.

**Comment by divyanshu013** [comment]
Hey @hb020 can you try after upgrading your node https://nodejs.org/en/

If you're unable to we should be able to do a release soon so you can try it on the hosted webapp without doing a build. Let me know

**Comment by hb020** [comment]
Thanks, it works. It would however be much nicer if we didn't need the click to see the contents. If it is possible to show truncated contents instead of the [...] on which we must click to see the contents, it would be much nicer.

**Comment by divyanshu013** [comment]
Awesome @hb020, right now we've fixed sized columns in DejaVu and an array can hold a large number of items due to which we've to go with this UX to keep things clean. Closing the issue for now :slightly_smiling_face:
