### ISSUE TITLE
chrome plugin: switching indexes does not update data in table view

### ISSUE THREAD

**Issue by jdc0589** [appbaseio/dejaVu#13]
In the chrome plugin, switching to a different index correctly updates the "Types" panel, but does **not** refresh the main data view.

Also, there isn't really much of a "loading" indicator or anything when connecting/switching types, which can be a bit disconcerting.

**Comment by siddharthlatest** [comment]
Confirming the behavior: when switching indexes, the data view doesn't change.

**Comment by siddharthlatest** [comment]
Fixed in the new release, [v0.4.2](https://github.com/appbaseio/dejaVu/releases/tag/v0.4.2). Also published in the chrome store.
