### ISSUE TITLE
importer can't work

### ISSUE THREAD

**Issue by hyf101070** [appbaseio/dejaVu#130]
I have install dejavu through docker in my server, while when I want use import feature, it show me this page, I tried to login by github or google, but all fail.

console print
`XMLHttpRequest cannot load https://accapi.appbase.io/user. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://<mydomain>:1358' is therefore not allowed access.`

**Comment by siddharthlatest** [comment]
@hyf101070 I know why you are seeing this issue. We allow authentication to happen only from whitelisted domains to prevent abuse. Both localhost and 127.0.0.1 are whitelisted but a custom domain wouldn't be.

I need to think more on what we can do for mitigating this.

**Comment by hyf101070** [comment]
Thank for your reply. So how can I use this feature in my server?

**Comment by siddharthlatest** [comment]
@hyf101070 Quick fix I can do is to whitelist your domain. What is the domain:port you plan to use dejavu on?

**Comment by hyf101070** [comment]
http://xmseapp01:1358/
tks

**Comment by siddharthlatest** [comment]
@hyf101070 Should work now.

**Comment by hyf101070** [comment]
@siddharthlatest  added. Thank you very much.

**Comment by hyf101070** [comment]
Hi @siddharthlatest , I have install dejavu in another two servers, but I have met the same problem again. Could you help add new url to whitelist again so that I can use this feature?

**Comment by siddharthlatest** [comment]
Sure, what's the new URL?

**Comment by hyf101070** [comment]
https://xxx/ 
https://xxx/
Thanks for your help.
@siddharthlatest

**Comment by siddharthlatest** [comment]
@hyf101070 Can you verify if these work?

**Comment by hyf101070** [comment]
@siddharthlatest Thanks, it works well now.
