### ISSUE TITLE
Modify one field multiple documents at once

### ISSUE THREAD

**Issue by philomatic** [appbaseio/dejaVu#131]
Dejavu is a great idea, I've been waiting for this! :)

One question / feature enhancement:

As a user in edit mode I'd like to modify one field of multiple documents at once with the entered value.

**Comment by siddharthlatest** [comment]
@philomatic Thanks! 

I am afraid that editing multiple documents at the same time can lead to accidental changes. What is the use-case you are trying to solve?

**Comment by philomatic** [comment]
Hmm... this could be solved with a special editing mode / confirmation query (like a pop-up).

I'm trying to categorize measured time series afterwards :)

So basically:

- Select 1-n documents (filtered by time / day or s.th. else)
- update a field like "category" or "time-series-id"

The time series are coming from a simple sensor which I don't want to update each measurement for a new time-series-id or similar.

However, this is just my current use-case. I wished I'd have that feature multiple times in the past:

A simple (ui driven) method to update multiple documents filtered by selection / query before.
By now, each time I have to write a http query or a little (java) script for this.

Best regards

**Comment by siddharthlatest** [comment]
Okay, I think this can be something we can support. We already have a **queries** view, we can possibly add a `update data` and `delete data` selections when creating a query to perform while keeping `view data` as the default action.

**Comment by philomatic** [comment]
Looking forward to test this!

By the way, you do have some nice ELK web UIs.
Happy to give them a test ride :)
