### ISSUE TITLE
importer time format error

### ISSUE THREAD

**Issue by hyf101070** [appbaseio/dejaVu#132]
When I use importer to import data to elasticsearch, I have a date filed like 
`"report_time": "2017-09-22T01:56:22"`
and dejavu parse data to format 'YYYY-MM-DDTHH:mm:ss'.
But when I start import data, it return with following error

`{
    "readyState": 4, 
    "responseText": "{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Invalid format: [YYYY-MM-DDTHH:mm:ss]: Illegal pattern component: T\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Invalid format: [YYYY-MM-DDTHH:mm:ss]: Illegal pattern component: T\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Illegal pattern component: T\"}},\"status\":400}", 
    "responseJSON": {
        "error": {
            "root_cause": [], 
            "type": "illegal_argument_exception", 
            "reason": "Invalid format: [YYYY-MM-DDTHH:mm:ss]: Illegal pattern component: T", 
            "caused_by": {}
        }, 
        "status": 400
    }, 
    "status": 400, 
    "statusText": "Bad Request"
}`

**Comment by divyanshu013** [comment]
@hyf101070 You are missing a 'Z' at the end of the date value (to denote the UTC Timezone). Reference: https://stackoverflow.com/questions/37148899/what-is-the-z-at-the-end-of-date-in-elasticsearch

Please try adding a **Z** at the end of date values like:
```
"report_time": "2017-09-22T01:56:22Z"
```

**Comment by hyf101070** [comment]
Thanks @divyanshu013 , it works welle now.

**Comment by hyf101070** [comment]
done.
