### ISSUE TITLE
Loading the /live endpoint fails using a dockerized image

### ISSUE THREAD

**Issue by brunifrancesco** [appbaseio/dejaVu#134]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

I'm having a llok at Dejavu deployed on my own server.

#### What is the version of Dejavu that you are using?
I'm using the last dockerized version

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

When I go to /live endpoint I have a Syntax Error in console e nothing shows on the page:

```
Uncaught SyntaxError: Unexpected token )
live.js:1 

Uncaught ReferenceError: help is not defined
    at Object.getInitialState (live.js:1)
    at new <anonymous> (live.js:1)
    at d._constructComponentWithoutOwner (live.js:1)
    at d._constructComponent (live.js:1)
    at d.mountComponent (live.js:1)
    at Object.mountComponent (live.js:1)
    at d.performInitialMount (live.js:1)
    at d.mountComponent (live.js:1)
    at Object.mountComponent (live.js:1)
    at i (live.js:1)
```

Thanks, 
cheers, 
FB

**Comment by brunifrancesco** [comment]
Got the same error using the Chrome extension (v 1.2.0).

**Comment by siddharthlatest** [comment]
@brunifrancesco I am not able to replicate this issue. Can you add a screenshot of when you are seeing this? Are you entering an app name and URL before seeing this issue?

**Comment by fjcamillo** [comment]
Also experiencing this error

Here's a screenshot:
<img src=https://ibin.co/3fsfsglogQ2T.png>

I'm also currently using the docker image appbaseio/dejavu:latest, although I am running dejavu on docker-compose with other images

here's my dejavu docker-compose code
```
dejavu:
    image: appbaseio/dejavu
    restart: always
    environment:
      VIRTUAL_HOST: <insert.virtual.host.name>
      VIRTUAL_PORT: 1358
```
I've also tried the importer end-point, it is running ok for me.

Thanks.

**Comment by siddharthlatest** [comment]
@fjcamillo @brunifrancesco I have tried the same image but am not seeing this. By looking at the error, I can make some guesses, but it would be great to be able to replicate this.

1. What is the OS/kernel/docker version you are using this with? 
2. Which browser do you see this on? Browser version?
3. What is the exact URL you are seeing this on?

**Comment by fjcamillo** [comment]
Hi @siddharthlatest, here's the environment I'm running it on

```
OS: Ubuntu 16.04.2 LTS
Kernel: 4.4.0-57-generic
Docker: 17.05.0-ce, build 89658be
Docker-Compose: 1.16.1, build 6d1ac21
Browser: Google Chrome Version 55.0.2883.75 (64-bit)
Exact URL: <defined.hostname>/live
```

Note: I'm currently not allowed to say the hostname. Sorry.

Thanks, also trying some tweaks on my side.

**Comment by siddharthlatest** [comment]
@fjcamillo Thanks, this has been helpful to replicate. The issue is happening on Chrome v55, and doesn't happen on Chrome v61 or newer (haven't tested the versions in between).

This is likely a polyfill issue, we will try to address it in the next release. In the meanwhile, if you are able to upgrade your browser, the issue won't appear.

**Comment by fjcamillo** [comment]
Hi @siddharthlatest Finally working on my side upgraded to Chrome v62. Big Thanks for the help and work done on dejavu

**Comment by brunifrancesco** [comment]
I can confirm it. Problem was an outdated version of Google Chrome. 
Got v62 and the application is up and running. 

Thanks for the support, 
FB
