### ISSUE TITLE
Failed to Update Child Documents

### ISSUE THREAD

**Issue by IdanWo** [appbaseio/dejaVu#139]
I'm using Dejavu 1.30 as Chrome Extention. 

When I try to update a child document (as part of parent child model), the update failes as the update request doesn't include the _routing nor _parent parameter. The exception got from elasticsearch: "Routing missing exception. Routing is required."

By the way, the user can't know that the operation failed since the application continue as usual.

**Comment by siddharthlatest** [comment]
Need to review how parent / child relationship works starting v6 onwards and if this is still relevant.

**Comment by siddharthlatest** [comment]
@divyanshu013 If we handle showing the exceptions when an update request fails as referenced in #127, this scenario should get handled as well.

**Comment by bstst** [comment]
I don't believe this should be closed, as the issue with updating child documents still persists. And the error description shown at the moment does not match the issue: right now the error is:

`Authentication Error`

, and the actual error is, for example, 

` {"error":"RoutingMissingException[routing is required for [messages]/[message]/[AV1-x9NPF9hjiuHhGF0Y]]","status":400}`

**Comment by siddharthlatest** [comment]
I agree, we should be showing the appropriate error message.
