### ISSUE TITLE
App is not loading in firefox

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/dejaVu#158]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
appbase

#### What is the version of Dejavu that you are using?
1.4

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
Dejavu is not able to open an app on firefox browser. Same works on chrome.
[Ref app](https://opensource.appbase.io/dejavu/live/#?input_state=XQAAAAJwAAAAAAAAAAA9iIqnY-B2BnTZGEQz6wkFsXzANcEiOj1t75YJPmGw7xeXjnOyOKwcTIJQljSmiDlmnS0idduXRCWx36R0WY9_Vp2OeiWvs5xdlMjiRDDupmmjgc5kXonz8uq6m2RqZAJEc_g63epaXVO0gRSbP_-KUQAA&editable=false)

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.
<img width="998" alt="screen shot 2018-01-22 at 4 14 55 pm" src="https://user-images.githubusercontent.com/6682655/35216980-98b2c260-ff8f-11e7-93d9-3d05e0cc553c.png">

**Browser**
Checked on Firefox 57 (macOS High Sierra) and Firefox 59 (linux x64 Ubuntu 16.04)

**Comment by divyanshu013** [comment]
We were using credentials in the url while fetching the esversion which firefox doesn't allow. Chrome automatically strips this out which is why it threw no errors. Upgrading appbase-js solved the problem of adding an empty body in the GET request for fetching types.

**Comment by roycwc** [comment]
I ran into this issue in self-host version and in appbase.io (as they are still v1.4)
It should update sooner as Firefox user are unable to use any function AT ALL.

**Comment by siddharthlatest** [comment]
@roycwc thanks for the pointer. It should work now when you use the hosted version -
 https://opensource.appbase.io/dejavu as well as on appbase.io. Will create a minor release for Docker and CE as well.
