### ISSUE TITLE
Custom Mirage URL

### ISSUE THREAD

**Issue by geraldclark** [appbaseio/dejaVu#168]
Is there a recommended approach for updating the mirage "Query View" url to a local docker instance of mirage?

**Comment by siddharthlatest** [comment]
@geraldclark I believe the place you can change this in the code is here - https://github.com/appbaseio/dejavu/blob/c5901fa91681e515f7335ef53f208f53c9ca5657/live/src/js/helper/urlShare.js#L107.

You can then build your own image using the Dockerfile.

**Comment by geraldclark** [comment]
@siddharthlatest Thanks identifying the code. As I mentioned on the mirage ticket (for visibility), I was just thinking it might be beneficial to allow for an external configuration as I'd prefer to not have to build a custom docker image or modify the core app source.

**Comment by siddharthlatest** [comment]
Linking to that thread - https://github.com/appbaseio/mirage/issues/56#issuecomment-370926849.

Happy to accept a PR for this or any other configuration use-cases that someone may have.

**Comment by geraldclark** [comment]
I don't mind taking a look. Would you be looking for this to be part of the initial app build process or would an ajax query fetching the config suffice?

**Comment by siddharthlatest** [comment]
@geraldclark That would be cool! I am thinking of this to be set as an ENV var which can be passed directly at Docker runtime. Something like `-E MIRAGE_HOST=http://localhost:3030`.

**Edit:** On a second thought, this would require the app build process to happen. 

What would an ajax query fetching the config look like?

**Comment by siddharthlatest** [comment]
This is not relevant anymore as we ship Mirage as `Query Explorer` within Dejavu itself.
