### ISSUE TITLE
Keeping state within dejaVu URL

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejaVu#17]
One of the key ideas for dejaVu is that it's a client side app and can be used within a browser or as an Elasticsearch plugin.

The idea is to capture dejaVu's state within it's URL: Things like ES host, index name, selected types, applied filters. That way, passing the state is as easy as sharing the dejaVu URL. Potential benefits are:

1. An easier way to debug while developing,  
2. Sharing public data sets in Elasticsearch would be super easy,

Of course, localhost URLs won't be accessible and there's a potential pitfall security concern wise (but if you were securing ES by obscurity, you have bigger problems).

**Comment by farhan687** [comment]
Feature added in master (Elasticsearch branch) and gh-pages branch.

Try this : http://appbaseio.github.io/dejaVu/live/index.html#?input_state=U2FsdGVkX1+f/C8kwCqv4uppG318VyZ65oBvj/qP792+6+ikK5uLKzX4e23oUKK+lX3Db16R6pG8M1MljRnIb+qOAAYog/TK6fYNQXtHtzMmvMl3r93DAWzAEzA1St3bSFbZ/QPJDPmK1UNyEuDkvhPT8jurH2kuW9d3sq+RYibIpo0AOEPxTNzWJY0ITBrN3/pzoVB6rmpo7+M1LoSoYcpTtBVfqSZMR/M8v/QKgdmk5aOnL1sLO53iSRQreZ1cKdpGtdx9WoFBEaRvlvVEW5te2Gtdn/ci9AHBXvaD0EE3pQL6vhPQtQ+MswJUxAq/vGhiZAHjqBBbDt7RyB0JkxMTTvnTbWTzpZsDEn2KxP02O96zqxzxuSHlE1qzCkhqqoKK67OLhZl7+c+S6mH3rMB3lCDFnRbMGljQO+JlRShEiKCir1UpzNScCNbF3X2C

**Comment by siddharthlatest** [comment]
Added column toggling in the state as well in https://github.com/appbaseio/dejaVu/commit/3d305edb03c156e0e8010e33e19dd832160521ce.

Feature now available in Elasticsearch plugin and in the [gh-pages](http://appbaseio.github.io/dejaVu/) branch.
