### ISSUE TITLE
be able to see the raw response from server

### ISSUE THREAD

**Issue by ataliadvanstep** [appbaseio/dejaVu#171]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Chrome extension

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
I would like to be able to see the raw answer from server because sometimes I need it for development

**Comment by siddharthlatest** [comment]
Can you elaborate on the request? I am not sure if this would be useful generally as you can get the raw response by looking at the network tab..

**Comment by ataliadvanstep** [comment]
@siddharthlatest totally right, I didn't think about this option. thanks
