### ISSUE TITLE
Web URL 404

### ISSUE THREAD

**Issue by AlexNodex** [appbaseio/dejaVu#172]
Your web URL in the main repo 404's!

**Comment by siddharthlatest** [comment]
Use this - https://opensource.appbase.io/dejavu-browser.

**Comment by AlexNodex** [comment]
I don’t need to use it. I was making you aware of an error.

**Comment by siddharthlatest** [comment]
It happened due to an inadvertent repo name change. Thanks for bringing it
up! I have just fixed the routing so the original URLs should work without
any change.
