### ISSUE TITLE
Bug: Filter dropdown UI doesn't go away after selecting a value

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejaVu#174]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

Hosted web app

#### What is the version of Dejavu that you are using?

1.5.0

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

The below GIF depicts the issue. When I select the `less than` filter here and **apply it**, it continues showing the dropdown UI even after the filter is applied.

![](https://camo.githubusercontent.com/41ea350669c6d2545060ba5a35c179713096ebaa/68747470733a2f2f692e696d6775722e636f6d2f577a53316b544e2e676966)

**Comment by MPierre9** [comment]
Hello! Do you mind if I try to fix this? Also any tips on where the bug may be located in the source code. Thanks!

**Comment by divyanshu013** [comment]
Hi @MPierre9! Please feel free to take this up.

I suspect this is an issue with react-bootstrap which we're using currently in dejavu. I fixed a similar issue with popovers where I'd to simulate a click outside by using `document.body.click()`. I think a similar fix should work here after the filters are applied. Check the `FilterDropdown` component at `live/src/js/table/FilterDropdown.js`.
