### ISSUE TITLE
Bug: Export UI modal shouldn't go away by clicking outside

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejaVu#176]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

Hosted web app

#### What is the version of Dejavu that you are using?

1.5.0

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

When in the process of exporting the data, if you click outside the modal area - the modal closes.

![](https://i.imgur.com/ta0rYA2.gif)

The above GIF shows this. Since exporting runs a scroll query to fetch all the data in the view, we shouldn't let a click outside the modal area to close the export modal.

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.

We should only close this modal if a user clicks on the close icon. And ensure there are no side-effects caused by this to the behavior of other modals.

**Comment by MPierre9** [comment]
Hey @siddharthlatest, do you mind if I work on this fix? :)

**Comment by siddharthlatest** [comment]
That would be awesome @MPierre9!
