### ISSUE TITLE
Allow viewing/selecting full field value in view mode

### ISSUE THREAD

**Issue by brylie** [appbaseio/dejaVu#178]
Using: Docker image

Version: 1.5.0

# Context
Some values in dejavu columns are truncated (with elepsis). This makes it impossible to select the field value in view mode.

# Feature request
When double clicking a field in view mode, the field should turn into a text box allowing full selection. Perhaps the text should be grey, indicating it is read only. Additionally, a 'copy' button might appear, copying text to clipboard when clicked.

# Related issue
Users have requested that columns could be resized (#5), probably due to the fact they cannot see/select the full value of field text.

**Comment by divyanshu013** [comment]
Hey @brylie, you can view the full text in view mode by clicking on the cell. For example:

![Screenshot](https://screenshotscdn.firefoxusercontent.com/images/a658927b-6076-40e9-aad1-52b0c2f4a456.png)

About #15, this is something in the roadmap :)

**Comment by brylie** [comment]
Hm, it may not be obvious. We even selected part of the text to copy and paste, and never say the popover.

**Comment by siddharthlatest** [comment]
Like @divyanshu013 mentioned above, the current behavior allows viewing the full text with one tap and selecting the full text with two taps (the latter is a standard web behavior) - you can then copy and text to get the full value.

We didn't opt for showing the full text popover on hover (or hover and 1-2s delay for example) as that may be an undesired behavior to some users. If there are ideas on how to make this more intuitive without hurting the user experience, we would like to consider them.

**Comment by siddharthlatest** [comment]
Closing this for now.
