### ISSUE TITLE
Adding a button "Select all / Unselect all"

### ISSUE THREAD

**Issue by rsareth** [appbaseio/dejaVu#18]
Hi,

Thank you so much for your Chrome extensions. Really helpful !

Can you add a button to (un)select all the results, please ?

My use case is to select all the result in order to delete them through your extension !

Thanks,
Rasmey

**Comment by siddharthlatest** [comment]
@rsareth Thanks for the support. We can add a button that toggles selection of all the results in the user's view.

**Comment by siddharthlatest** [comment]
"Select / Unselect All" feature has been added and published as part of v0.6.0 release on the [chrome webstore](https://chrome.google.com/webstore/detail/dejavu/lcanobbdndljimodckphgdmllahfcadd?hl=en).
