### ISSUE TITLE
Date format overrides

### ISSUE THREAD

**Issue by brylie** [appbaseio/dejaVu#180]
using: Docker
version: 1.5.0

# Context
Dates are stored in ElasticSearch in various format (such as Unix timestamp). These dates are displayed to the end-user in raw form.

# Feature request
It would be nice to be able to add a custom formatter to date fields, so they could be displayed in various formats (such as YYYY-mm-dd).

**Comment by siddharthlatest** [comment]
I think currently we show the dates in the specified format in Elasticsearch. For instance, if you set the format (i.e. mapping in ES) as `YYYY-mm-dd`, the data in dejavu should also appear in the same format.

Do you see otherwise?

**Comment by brylie** [comment]
Well, if a human is reading the table, the format should be human readable - even if it is stored as unix timestamps. There could be other use cases, such as date localization or displaying in local timezone. So, a 'date renderer' could allow some decoupling of the underlying data from output/filter widgets.

**Comment by siddharthlatest** [comment]
Dates are shown in a human-readable form starting with the latest `3.0.0` release 🎉 .
