### ISSUE TITLE
Create new query from current filters

### ISSUE THREAD

**Issue by brylie** [appbaseio/dejaVu#182]
using: Docker
version: 1.5.0

# Context
Users can currently filter one or more ES columns in the table view. They can also define queries via a separate process, by inputting raw ES query JSON.

# Feature request
It would be useful if the user could quickly create a new ES Query by 'saving' the current table filter settings.

**Comment by siddharthlatest** [comment]
@brylie It's a good idea, however I am not sure how feasible it is - both technically and how to keep it intuitive. Although I will leave this open for a bit if someone is interested in picking it up.

We do have another project https://opensource.appbase.io/mirage/ that allows creating ES queries via a GUI. We already link to that in dejavu in the top left area. ![](https://i.imgur.com/NWsJUj3.png)

**Comment by brylie** [comment]
Any plans to unify the projects? They seem like peanut butter and jelly.

**Comment by siddharthlatest** [comment]
Mirage - the query builder project is written in Angular/Typescript and Dejavu is in React, so it's hard to bring them together in the near term.

I think there can be a helper icon in the Query Tab, where we can show a link to Mirage - where a user can go and bring the generated DSL back.

That said, I am not entirely happy with our current UI view for queries and types sidebar (now that multi-types are gone with ES 6+) and want to pan that out better before doing anything deeper here.

**Comment by siddharthlatest** [comment]
Full context: Both projects are unified now. There's a `Query Explorer` tab available in Dejavu which lets a user write queries.
