### ISSUE TITLE
Add inline documentation (or at least links to online docs)

### ISSUE THREAD

**Issue by brylie** [appbaseio/dejaVu#183]
# Context
Some aspects of the dejavu UI are somewhat ambiguous, such as the 'has' filter. From what we can see, there is no link to any form of documentation either in the README or on the official website (aside from some demo videos).

# Feature request
Help users to learn dejavu by providing rich documentation. This could be in the form of inline help texts (or popovers), or even just a user manual.

**Comment by siddharthlatest** [comment]
It's definitely a good idea. Do you have specific things you felt unsure about besides the 'has' filter?

A good starting point is for us to add `info` icons with tooltips - we already do that in certain places.

**Comment by brylie** [comment]
We were also wondering about valid date strings for date filters.

**Comment by siddharthlatest** [comment]
- [x] Add an info tooltip for the `has` filter.
- [x] Add an info tooltip for the date filters.

@divyanshu013 Can you expand on how one can implement these?
