### ISSUE TITLE
Visual query builder

### ISSUE THREAD

**Issue by brylie** [appbaseio/dejaVu#185]
# Context
dejavu currently requires the user to create ES queries by manually writing ES Query DSL JSON.

# Feature request
Allow users to create queries by some combination of table filters and visual query builder UI.

# Example screenshot
[Grafana](https://grafana.com/) has a visual query building UI for some of its data sources:

![screenshot_20180323_120012](https://user-images.githubusercontent.com/17307/37823372-f8c541d8-2e91-11e8-9c28-fc1ee9318fca.png)

**Comment by siddharthlatest** [comment]
This has been added in 2.0. See the `Search Preview` tab.
