### ISSUE TITLE
Empty Page is Displayed

### ISSUE THREAD

**Issue by sahadevan** [appbaseio/dejaVu#189]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Through Local Build.

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.
![image](https://user-images.githubusercontent.com/6292490/38087302-40ff52e4-3375-11e8-8bed-131ec6f4a11d.png)

**Comment by siddharthlatest** [comment]
@sahadevan Did you do a `bower install`? It looks like some of the dependencies haven't been installed.

**Comment by siddharthlatest** [comment]
Closing this one, feel free to report back if it's something else.
