### ISSUE TITLE
Query view never shows more than 20 documents

### ISSUE THREAD

**Issue by al-serebrov** [appbaseio/dejaVu#193]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Docker image, Chrome extension (tried both)

#### What is the version of Dejavu that you are using?
1.5.0

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
If I create a very simple query, for example:
```json
{
    "query": {
        "match_all": {}
    }
}
```

And scroll down, DejaVu doesn't show more than 20 documents, at the same time an error in JS appears:

```js
Uncaught TypeError: typeName.join is not a function
    at paginationSearch (feed.js:295)
    at Object.paginateData (feed.js:395)
    at Object.paginateData (homePageHelper.js:326)
    at Object.handleScroll (live.js:1)
    at r (live.js:1)
    at c (live.js:1)
    at HTMLTableSectionElement.y (live.js:1)
```

Please help me to identify whether the issues is on my side.

##### If your issue deals with accessing Elasticsearch cluster, share the necessary steps to replicate the behavior (the configuration.yml settings, where your ES cluster is hosted, any relevant logs).
Issue replicates for me both on application running in the Docker container and in the one running as a chrome extension, again both on remote and on local ES with different elasticsearch.yml, e.g. locally I have these settings for CORS:

```
http.port: 9200
http.cors.allow-origin: "*"
http.cors.enabled: true
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.allow-credentials: true
```

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.
![peek 2018-04-02 17-17](https://user-images.githubusercontent.com/24430812/38199598-02467cc6-369a-11e8-923f-f6194c8fdc52.gif)

**Comment by divyanshu013** [comment]
Hi @al-serebrov what is your elasticsearch version?

**Comment by al-serebrov** [comment]
Hi @divyanshu013 2.3.4.

```
version": {
"number": "2.3.4",
"build_hash": "e455fd0c13dceca8dbbdbb1665d068ae55dabe3f",
"build_timestamp": "2016-06-30T11:24:31Z",
"build_snapshot": false,
"lucene_version": "5.5.0"
},
```

**Comment by divyanshu013** [comment]
Got it, I'm able to replicate the issue. Will keep you posted here. Thanks for reporting!
