### ISSUE TITLE
Weird behavior with multiple queries

### ISSUE THREAD

**Issue by al-serebrov** [appbaseio/dejaVu#194]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Docker image, Chrome extension (tried both)

#### What is the version of Dejavu that you are using?
1.5.0

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
That's pretty hard to explain because the behavior is unexpected and unpredictable.
Steps to replicate:
1. Go to "Queries"
2. Create more than one query, preferably with different "body"
In my case:
query1:
```json
{
    "query": {
        "match_all": {}
    }
}
```

query2
```json
{
    "query": {
        "match": {
            "price": 19.99
        }
    }
}
```

3. There is no radio button to switch between queries, so you need to "Edit" -> "Apply query" to switch to another one

4. Switch between them multiple times. You may notice the following:
- query body is replaced by another one, e.g. query1 now have body from query2
- inactive query is still highlighted (which is confusing a bit)
- if you have more than 2 queries, e.g. three of them one could just disappear from time to time

##### If your issue deals with accessing Elasticsearch cluster, share the necessary steps to replicate the behavior (the configuration.yml settings, where your ES cluster is hosted, any relevant logs).
Configuration is the same as in issue #193 
Elasticsearch version is 2.3.4

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.
On the following short video you can see that query1 gets replaced by query2, also something goes wrong when applying the queries.

![peek 2018-04-02 17-38](https://user-images.githubusercontent.com/24430812/38200394-d1674290-369c-11e8-943c-523c0b8a2e6c.gif)

**Comment by al-serebrov** [comment]
Please let me know if you are able to replicate the issue.

**Comment by siddharthlatest** [comment]
@al-serebrov Thanks for reporting this. I am able to replicate the issue. We will try to fix this in the next release.

**Comment by al-serebrov** [comment]
Thank you very much for the fix!
