### ISSUE TITLE
Cant connect to Elastic on the importer view

### ISSUE THREAD

**Issue by j0an** [appbaseio/dejaVu#196]
I'm running on a docker environment.

#### This is my ES config file

```
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.allow-credentials: true
network.host: 0.0.0.0
http.port: 9200
discovery.zen.minimum_master_nodes: 1
xpack.license.self_generated.type: basic
xpack.security.enabled: false
```

### http GET to http://0.0.0.0:9200/
```
{
"name": "tYDoYiX",
"cluster_name": "sancor-cluster",
"cluster_uuid": "kGBNFqtQS1as-5htf8k_ww",
"version": {
"number": "6.2.2",
"build_hash": "10b1edd",
"build_date": "2018-02-16T19:01:30.685723Z",
"build_snapshot": false,
"lucene_version": "7.2.1",
"minimum_wire_compatibility_version": "5.6.0",
"minimum_index_compatibility_version": "5.0.0"
},
"tagline": "You Know, for Search"
}
```

### I got access on the "live" section 👌 

screenshot: https://cloudup.com/cwcEiIQErBX

## The error appears when I try to connect to the importer section

screenshot: https://cloudup.com/cx6RIg23Q3Y

**Comment by siddharthlatest** [comment]
@j0an Thanks for the issue, on a first glance - I think I understand why this is happening.

Also currently, we need to extend support of importing data mappings to ES v6, see #195.

Will keep the progress posted over here.

**Comment by j0an** [comment]
oh @siddharthlatest, thanks for the quick response. I subscribed to that issue waiting for news :)

**Comment by siddharthlatest** [comment]
Sorry for the delay on this, but importing data to Elasticsearch v6 is now supported. 🎉
