### ISSUE TITLE
Define Index Patterns

### ISSUE THREAD

**Issue by pingz** [appbaseio/dejaVu#197]
I'm just trying Chrome extension version 1.6.1, and I use elasticsearch as a primary log sink. As most of log handler will create index daily, so this is very import to [define index patterns](https://www.elastic.co/guide/en/kibana/current/tutorial-define-index.html).

Maybe I miss something, but I can't find anything about this feature. Would someone give me some clues about it?

**Comment by siddharthlatest** [comment]
We currently don't support index patterns (or multi-index views) in dejavu. I will add it as a feature request.

**Comment by siddharthlatest** [comment]
This would require us to support multi-index views. I can't think of a way to do this without having that first. Is that an accurate interpretation @pingz?

**Comment by pingz** [comment]
@siddharthlatest  I'm not very well at react.js development, but I thought the view shall be same, you just need to use [wildcard index pattern](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/multi-index.html#multi-index) instead of single index name, you may need to implement some views and services for creating and fetching an index pattern (maybe also using elasticsearch as storage backend).

**Comment by siddharthlatest** [comment]
Supporting wildcard pattern inherently means a multi-index view support. We have to think about how to handle the tabular view (two indexes can potentially have vastly different mappings), all our underlying API calls (for bulk delete, update_on_query, etc) may now occur on more than one indexes.

If you are interested in Dejavu listing current indices in the cluster for easy access, we have added that in the 1.6 release.

**Comment by pingz** [comment]
@siddharthlatest I get your point. Of course it is great using a multi-index view to support different mappings.

I usually just deal with the data using same mapping indexes, To my understand kibana can't show fields if there is a type conflict among the indices. The catch is that if you want to do data visualization or some another complex tasks, you will eventually run into some troubles if the field types are not matched exactly. That's why I misunderstood what you mean at first place.

**Comment by siddharthlatest** [comment]
Support for multi-index views has been added in the `next` version of dejavu. Will be out in the next release.

**Comment by danielo515** [comment]
Sorry but I am not able to run query maker on multi-index views. How is it supposed to work?

**Comment by siddharthlatest** [comment]
@danielo515 Currently, the query view only works per single index. Since it's GUI based and guided, we need to fetch the mappings (something that multiple indexes would complicate).

**Comment by danielo515** [comment]
Can't you just assume the schema is the same? Or add a flag to allow the user to take the risk? In my case I know all the indexes will have the same schema

**Comment by siddharthlatest** [comment]
@danielo515 In that case, you can connect to one of the indexes. The generated URL for the query is editable, you can change it prior to firing the query. :-)

**Comment by danielo515** [comment]
Cool, that looks like a feasible workaround. Thanks @siddharthlatest
