### ISSUE TITLE
Avro record(having hierarchies) is not getting displayed properly on dejavu UI 

### ISSUE THREAD

**Issue by jay999123** [appbaseio/dejaVu#199]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

using appbaseio/dejavu

#### What is the version of Dejavu that you are using?
I'm not sure as I'm using the docker compose to pull the dejavu (PLUGINS: appbaseio/dejavu)

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

> I'm doing Kafka - Elasticsearch integration in which dejavu is providing the UI portion for ES. I've Avro type records in my topic (_test_topic_) and each record is having hierarchies. When the data gets into the ES, the dejavu is not getting displayed properly. Something like in the below screenshot:
And there is no search to filter the records.
I've tried using the query, but not returning the results (not sure if I'm wrong somewhere)

_{
    "query": {
        "match": {
            "type": "s12348988"
        }
    }
}_
![image](https://user-images.githubusercontent.com/7712148/38846707-d73f7acc-41cb-11e8-9897-7a1c0864f9e8.png)

##### If your issue deals with accessing Elasticsearch cluster, share the necessary steps to replicate the behavior (the configuration.yml settings, where your ES cluster is hosted, any relevant logs).

**My ES properties are given below:**

_name=elasticsearch-test15-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=test_topic
connection.url=http://localhost:9200
type.name=kafka-connect-test15
transforms=createKey
transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.createKey.fields=KEY_NUMBER_

**My record sample:**

_{
	"KEY_NUMBER": "ABC87764448"			**//MyKEY**
}

				//**Value**startsfromhere
{
	"record001": {
		"com.hello.record001": {
			"PARAMETER1": { "string": "90"},
			"PARAMETER2": { "string": "AJ"},
			"record0011": {
				"array": [{ 
					"NAME1": {"string": "ANN"},
					"NAME2": {"string": "PLM"}},
				   {
					"NAME1": {"string": "ANN11"	},
					"NAME2": {"string": "PLM22"	}},
				]
			},
			"record0012": null,
			"record0013": {
				"com.hello.record0013": {
					"NAME2": {"string": "Hello"}
				}
			},
			"record0013": {
				"array": [{
					"NAME1": {"string": "Hello"},
					"NAME2": {"string": "POLP"},
					"record001112": {
						"array": [{
							"NAME": {"string": "HJ"},
							"FIRST": {"string": "M"}
						}]},]}}]},
		"RECORD002": {
			"com.hello.RECORD002": {
				"DAY": {"string": "  "},
				"WORK": {"string": "OKII"}
			}}}
}_

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.

Screenshot mentioned above.

Please let me know if I'm missing anything.
Thanks!!

**Comment by siddharthlatest** [comment]
Currently, filters and UI view in dejavu (breaking of columns) is supported for top level fields in a document.

If it is possible to not embed the data within `record#` top level field, dejavu should be able to display data columns.

**Comment by jay999123** [comment]
Hi @siddharthlatest , Thanks for the reply. 
This is how my schema is which I cannot change. Is there any other way?

What about querying the data? like below:
   _{
       "query": {
            "match": {
                 "type": "s12348988"
                          }
                    }
    }_

The above query is not returning any result.(even though the record is present on the UI). Is the query that I'm doing in the proper way?

**Comment by siddharthlatest** [comment]
@JanardhanVarikuti I don't see a `type` field in the above record sample. You need to have a field (or a nested field) in your mapping for the query to return something in the UI view.

**Comment by jay999123** [comment]
@siddharthlatest There is something called "_type/id_" column where my key is displayed. I'm trying to query by using my key(here it's _s12348988_ ) so that I can get the corresponding record (here it's corresponding _record001_)

**Comment by siddharthlatest** [comment]
@JanardhanVarikuti `ids` query is what you are looking for then - https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-ids-query.html.

**Comment by jay999123** [comment]
@siddharthlatest will check and let you know the result. Thanks.

**Comment by jay999123** [comment]
Hi @siddharthlatest, I'm bale to query the records with `ids` query. Thanks. 
But are you planning to include the feature of displaying the hierarchies of the records(avro) into separate columns any time soon?

**Comment by siddharthlatest** [comment]
@JanardhanVarikuti awesome!

We are considering building alternative views to tabular view, like a list view.

There can also be a possibility to expand the object view when viewing tabular data, but I am not sure how feasible the latter is. It then makes editing the data that much more tricky, partial updates to a document only work at the top-level field in ES.
