### ISSUE TITLE
limit which indexes can be edited manually

### ISSUE THREAD

**Issue by jdc0589** [appbaseio/dejaVu#2]
It would be great if there was a config option to make everything readonly, unless an index/type was whitelisted as write enabled. This doesn't exist already does it?

**Comment by siddharthlatest** [comment]
Is the idea to prevent accidental read / writes from the browser interface? We don't support modifying data in place and a user needs to explicitly confirm before making any CUD modifications.

Or is the idea to prevent writes the index / type at the database level?

**Comment by jdc0589** [comment]
not really. ive got 1 index that i need a fee people to be able to edit
manually,  but never any of the others.

**Comment by siddharthlatest** [comment]
That can be done with access permissions, i.e. generating credentials (tokens) that have read only permissions and another set that have write permissions. We support this use-case in appbase.io http://news.appbase.io/new-dashboard-features/. People with latter can then edit data with dejavu while those with read only permissions can only see the data.

**Comment by siddharthlatest** [comment]
Closing this issue, as security permissions are better handled at the Elasticsearch / hosting layer.
