### ISSUE TITLE
folder/filename as ID

### ISSUE THREAD

**Issue by logemann** [appbaseio/dejaVu#202]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

Docker Image

#### What is the version of Dejavu that you are using?

1.6.1

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

I want to store a folder/filename as ID in elasticsearch. When doing it via cURL directly, i do:

`
curl -X PUT "localhost:9200/okaydocs/files/aha%2Ffoo.pdf" -H 'Content-Type: application/json' -d'
{
    "Bucket" : "kimchy",
    "Name" : "foo.pdf"
}
'
`

I can delete this easily via cURL:

`
curl -X DELETE "localhost:9200/okaydocs/files/aha%2Ffoo.pdf"
`

But when trying to delete it via dejavu, i am getting error because urlencoding will not be used by the webapp.

vendor.min.js:7 DELETE http://localhost:9200/okaydocs/files/aha/foo.pdf? 400 (Bad Request)

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.
not needed

**Comment by siddharthlatest** [comment]
@logemann I understand the issue. However, ES doesn't return back the id (via _search endpoint) as `aha%2Ffoo`, but as `aha/foo`.

How can dejavu know what ids to transform?

**Comment by logemann** [comment]
Dont understand the question. Why dont u just urlencode the ID which you get back from ES and use this for subsequent requests?

**Comment by siddharthlatest** [comment]
I am thinking about whether this will have any side-effects. I am trying to find any reading on how Elasticsearch handles URL encoding across versions.

**Comment by logemann** [comment]
according to ElasticSearch Reference documentation "/" is a valid character for an ID as are other chars like ".". Given thats the case, an application should handle this scenario. Especially if its a web viewer client for ES ;-)

**Comment by siddharthlatest** [comment]
- [ ] Update: We will add URLEncode(..) to all Ids being indexed into Elasticsearch. This will apply to all `Insert JSON` and `Update` requests, as well as when importing via importer.
