### ISSUE TITLE
Cannot edit cells of 'Keyword' fields 

### ISSUE THREAD

**Issue by musicist288** [appbaseio/dejaVu#206]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
I've tried all of them.

#### What is the version of Dejavu that you are using?
329f1006bd38736504e42223e7e2d23c80e04977

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
When trying to edit a keyword field, the error: "This field should be a number" prevents me from entering anything other than a number. The keywords I need to enter are not numbers.

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.
![screen shot 2018-05-03 at 8 53 31 am](https://user-images.githubusercontent.com/368976/39577506-8859077a-4eaf-11e8-95dd-8f1a521e326b.png)

**Comment by siddharthlatest** [comment]
@musicist288 Can you share the mapping for this field? You can view it by clicking on the message icon to the left of your field.

**Comment by musicist288** [comment]
Sure:
![screen shot 2018-05-03 at 9 26 27 am](https://user-images.githubusercontent.com/368976/39579177-18be024e-4eb4-11e8-8b31-568f86ba7167.png)

**Comment by musicist288** [comment]
I was able to get my local copy working by changing https://github.com/appbaseio/dejavu/blob/dev/live/src/js/table/Cell.js#L257 to:
```JS
if (this.props.datatype.type !== 'string' && this.props.datatype.type !== 'text' && this.props.datatype.type !== 'keyword') {
```

I don't know if this is the correct solution, but it worked for me.

**Comment by divyanshu013** [comment]
Hi @musicist288, this looks like the correct solution, we actually use `keyword` as a nested multifield by default which is why we missed out this usecase. Would you like to send a pull request with the fix? 🙂
