### ISSUE TITLE
How to use dejavu with elasticsearch on local running it from opensource.appbase.io 

### ISSUE THREAD

**Issue by hgc2002** [appbaseio/dejaVu#208]
"I wanted to use the wonderful dejavu software to audit a local elasticsearch instance. 

Wondefull idea, but currently it looks that it's not easy as it should be. But I found a way to do it, and that's what I want to share with Community."

Here is the link to the full article: https://stackoverflow.com/questions/50231296/how-to-use-dejavu-for-elasticsearch-on-local-running-it-from-opensource-appbase

**Comment by siddharthlatest** [comment]
Good point @hgc2002. We can add an accessibility feature to show a helpful message on how the user can disable `mixed content browser warning` to view their http:// URLs.

Happy to take in any PRs related to this. The idea is when a user connects to `http://` scheme URL in their URL input, we want to display an error dialog (by detecting user's browser) on how they can enable showing mixed content. Reference - https://kb.iu.edu/d/bdny#view.
