### ISSUE TITLE
Host dejavu at root path

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejaVu#210]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
All

#### What is the version of Dejavu that you are using?
Latest

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
Currently, dejavu lives at `/live` endpoint. This creates a complexity on the user end if you were to host dejavu at a non-root domain, e.g. if dejavu resided inside of `example.my-domain.com/dejavu` path, it can be a bit complex to get the routing done in a generic fashion (since we ourselves do a redirect if a request comes at '/' to route to '/live'.

We can simplify this scenario (and possibly others) by simply putting dejavu at '/'.

**Comment by divyanshu013** [comment]
@siddharthlatest we can now host dejavu at `/`. It'll also work at `/live` for backward compatibility (with some missing images). Before deploying we should set up the route redirection for old blog post or docs links.
