### ISSUE TITLE
One Question

### ISSUE THREAD

**Issue by roysoham** [appbaseio/dejaVu#213]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Ubuntu 16.04

#### What is the version of Dejavu that you are using?
Latest 

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
One Question is this FREE ?

**Comment by divyanshu013** [comment]
FREE as in FREEDOM :)

**Comment by roysoham** [comment]
FREE as in Opensource free, freedom means different things to different people, anywayz closing this, uninstalled it not worth the time, or money

**Comment by divyanshu013** [comment]
https://en.wikipedia.org/wiki/Free_and_open-source_software
