### ISSUE TITLE
Unexpected ReferenceError: LZMA is not defined fron running DejaVu as a local web app

### ISSUE THREAD

**Issue by hmachefe** [appbaseio/dejaVu#220]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Hosted web app

#### What is the version of Dejavu that you are using?
1.6.1

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
![image](https://user-images.githubusercontent.com/4142280/42340037-daec5300-805c-11e8-93a0-c78a24591a99.png)

I keep trying to run dejavu locally as a web app on top of **ElasticSearch**, started this way: `yarn start` directly meaning regardless of docker, and rendered through Firefox: http://localhost:1358/live/

However I have this error raised in `console.log` (web inspector tab). 

```
[WDS] Disconnected!  live.js:25809:5
ReferenceError: LZMA is not defined[Learn More]  JSONURL.js:1:7
[HMR] Waiting for update signal from WDS...  live.js:25941:2
Download the React DevTools for a better development experience: https://fb.me/react-devtools
live.js:46069:9
ReferenceError: Auth0 is not defined[Learn More]

```

I haven't noticed any logs error that node would have compained about. ElasticSearch logs do not complain either. I paid attention to specify CORS rules in `./config/elasticsearch.yml` as expected.

**Comment by siddharthlatest** [comment]
There are some bower dependencies, can you run `bower install`?

**Comment by siddharthlatest** [comment]
Closing this as it's related to a missing installation step. We have also just migrated off Bower so this shouldn't even happen after the upcoming release.
