### ISSUE TITLE
Problem on connection

### ISSUE THREAD

**Issue by gabriel-tessier** [appbaseio/dejaVu#223]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Chrome extension

#### What is the version of Dejavu that you are using?
Certainly last version installed 10 minutes ago.

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
I installed the chrome plugin and tried to connect by typing "127.0.0.1:9200" then the input was freezed and can do nothing, tried to refresh several time close open the tab, then I had a white page.
Elasticsearch was not running I was expecting something like a timeout or an error message but nothing.

Second try: I uninstall the plugin and install again, this time the login page was back. I type again 127.0.0.1:9200, but this time elasticsearch was running, I was able to access via curl.
Same problem, after several refresh I was able to delete the first input and notice that maybe need to put http://127.0.0.1:9200 so I tried to type in the input but it was in readonly or blocked I was not able to type inside, but when I clicked on run one pop-up appear with error message that the address is mandatory, I forget about the exact message.
Anyway the test to check if the field is empty work correctly!
If you can add a test to check the format if it must start with http:// or set a timeout or something to tell the user that you try to connect "wait 10 sec." (inform about the time of the timeout), it can be very helpful.
I'll give a try again later and hope that I can connect.

Hope it help.

##### If your issue deals with accessing Elasticsearch cluster, share the necessary steps to replicate the behavior (the configuration.yml settings, where your ES cluster is hosted, any relevant logs).

No problem with elasticsearch as I can access with kibana, cerebro and curl.

**Comment by divyanshu013** [comment]
The homepage is being redone so we could partially tackle a few issues here. Hope you were able to connect with `http://`

**Comment by siddharthlatest** [comment]
This shouldn't be a problem with the latest release `3.0.1` on Chrome Store.
