### ISSUE TITLE
Add a possibility to pass default URL and index name via environment to automatically connect 

### ISSUE THREAD

**Issue by usmanovbf** [appbaseio/dejaVu#225]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

Docker Image
#### What is the version of Dejavu that you are using?
1.7
#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
Feature request: add a possibility to pass default URL and index name via environment to automatically connect. It is frustrating me to write url and index every time

**Comment by divyanshu013** [comment]
Possible duplicate #205
