### ISSUE TITLE
upgrade to appbase-js@4.0.0-beta

### ISSUE THREAD

**Issue by metagrover** [appbaseio/dejaVu#231]
Search Preview uses the latest appbase-js, which doesn't work with current dejavu codebase, causing the entire app to crash. Please upgrade to latest `appbase-js` to fix this behavior.

**Comment by divyanshu013** [comment]
Fixed via https://github.com/appbaseio/dejavu/commit/17c53024913d4b74034217d110cf404f40ab5ea8
