### ISSUE TITLE
Authentication and Authorization

### ISSUE THREAD

**Issue by rajagottumukkala** [appbaseio/dejaVu#243]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Chrome Extension 

#### What is the version of Dejavu that you are using?
2.0.5

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
Is it possible to implement Authentication and Authorization with in Dejavu? 
We want to build a Search UI for some users, but they don't need to update any data. Is there a way to disable some action and some pages in the UI? 
Is there a way to add custom filters on top of user's search criteria? for example, if user is searching for "something" we want to add a filter on the field "created_by" for that user? We do not have permissions applied to the data directly so we need to use multiple fields to identify if a user can see a document or not.

**Comment by siddharthlatest** [comment]
Dejavu uses Elasticsearch as its backend. By itself, it's agnostic to how authentication/authorization happens. However, if your backend service supports this, it should be possible via Dejavu.

> We want to build a Search UI for some users, but they don't need to update any data. Is there a way to disable some action and some pages in the UI?

This isn't possible. You can set a default view, but the user can change it. You might want to check https://github.com/appbaseio/reactivesearch for building a custom search UI.
