### ISSUE TITLE
【Search Preview】filter can't display list data in dataset

### ISSUE THREAD

**Issue by JacobHZ** [appbaseio/dejaVu#248]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Chrome extension

#### What is the version of Dejavu that you are using?
latest

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

I have data type like the picture below:
![image](https://user-images.githubusercontent.com/15662990/47496438-5ac85e00-d889-11e8-908e-81f75fe57156.png)
When I work with Search Preview to add new filter:
![image](https://user-images.githubusercontent.com/15662990/47496524-95ca9180-d889-11e8-9e11-4926dfe97115.png)
The result turned to be blank:
![image](https://user-images.githubusercontent.com/15662990/47496555-b8f54100-d889-11e8-8bff-4ad81c7cabfc.png)

**Comment by siddharthlatest** [comment]
Hi @JacobHZ, this has been fixed but requires a significant change in state management on Dejavu's end. It will be out in the next release.

In case you are using appbase.io, the change is already available in the dashboard.

**Comment by siddharthlatest** [comment]
This should work now with `3.0.0` release, also available on the Chrome Store.
