### ISSUE TITLE
bug: white screen when loading dejavu

### ISSUE THREAD

**Issue by samthomson** [appbaseio/dejaVu#249]
docker-image dejavu, but previously tried the extension and had I think the same issue.
version: appbaseio/dejavu:latest

I go to localhost:1358 and try to connect to the elasticsearch instance. It times out so I attempt to reload, but then just get a blank screen. Opening the console shows some errors perhaps. I've attached a screen-shot.

Any ideas?

![image](https://user-images.githubusercontent.com/6588340/48063656-1bd4c980-e1f4-11e8-8a15-2c623a097966.png)

**Comment by siddharthlatest** [comment]
@samthomson Can you share how you are setting the URL? We expect a fully qualified URL, in `http://my-elasticsearch:port` format.

**Comment by henrikbak** [comment]
I had the samme issue. I was missing the protocol in the URL.

The problem is that you are presented with the white screen afterwards, so you can't change the URL in any way. Some validation in the form would do wonders.

**Comment by siddharthlatest** [comment]
Good feedback, we're building a new version of Dejavu (`next` branch) and will include proper error checking over there. cc @lakhansamani

**Comment by samthomson** [comment]
@henrikbak did you find a way to update the URL after you'd entered it without the protocol? 
@siddharthlatest Is there anything cached locally I can delete to get me back to the 'front' page. Or is there a latest version I can use. I'm using the docker image, added to my docker-compose file as `appbaseio/dejavu`

**Comment by samthomson** [comment]
Nevermind, I resolved the issue myself somewhat. I updated my docker-compose to use a different image `appbaseio/dejavu:3.0.0-alpha` and now it works :fireworks: :tada:
