### ISSUE TITLE
plaintext password in UI

### ISSUE THREAD

**Issue by clem-compilatio** [appbaseio/dejaVu#25]
Hello, in the UI, the password is entred in plaintext as part of the connection url (http(s)://user:pass@server:port).
After connection, le url - with the plaintext password - is still displayed.
=> Anyone who looks at my screen can see my credentials.

Could you update your UI to hide the password please ?

**Comment by siddharthlatest** [comment]
@clem-compilatio: yes, this will be added in the next release.

**Comment by siddharthlatest** [comment]
Added in ``v0.7.1``. Chrome app link: http://chrome.google.com/webstore/detail/dejavu/lcanobbdndljimodckphgdmllahfcadd?hl=en

**Comment by clem-compilatio** [comment]
thanks
