### ISSUE TITLE
Not able to access url params in ReactiveList

### ISSUE THREAD

**Issue by lakhansamani** [appbaseio/dejaVu#250]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

`next` branch of Dejavu
#### What is the version of Dejavu that you are using?
`next`

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

The issue is because of the ReactiveList which is not able to read URL params
Watch: https://github.com/appbaseio/reactivesearch/issues/607

##### If your issue deals with a UI issue, share with us a screenshot of the failing network request or the browser console log showing the error.

https://www.dropbox.com/s/mzkijsvlcxzo2r0/Screenshot%202018-11-21%2018.31.38.png?dl=0

**Comment by redlinecodes** [comment]
@lakhansamani - any solution to this. I've been getting the same error :(

**Comment by lakhansamani** [comment]
@redlinecodes not yet we are working on it

**Comment by siddharthlatest** [comment]
@lakhansamani Can this work now with ReactiveSearch 3.0?

**Comment by lakhansamani** [comment]
> @lakhansamani Can this work now with ReactiveSearch 3.0?

No this is not fixed yet

**Comment by lakhansamani** [comment]
Fixed in https://github.com/appbaseio/dejavu/commit/f4e2592d7ca85deb0b9c43307c513ec6bd7df58c
