### ISSUE TITLE
SearchPreview filters are not connected in the UI

### ISSUE THREAD

**Issue by ilulir** [appbaseio/dejaVu#251]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Chrome extension

#### What is the version of Dejavu that you are using?
2.0.5

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.
Using the SearchPreview tab, define several filters and enable the Count for each record. When selecting a value, it would be extremely helpful for all other filters to update the count of their records based on the filter already selected

**Comment by siddharthlatest** [comment]
@ilulir We don't want to include this as a default behavior in the Search Preview UI as it triggers extra queries, and can cause a rate limit error (when using multiple facets) on freely hosted appbase.io apps.

However, this can be done when you export the code to Codesandbox as the underlying library that is used for Search Preview supports this via the [`react` prop](https://opensource.appbase.io/reactive-manual/list-components/multilist.html#props). You can also do so much more. :-)

Hope this helps!

**Comment by acosta-edgar** [comment]
What about updating the filter counts after a search is executed?
Currently, whenever I perform a search, the filter option numbers don't get updated, which kind of renders the filters useless.

Now, it does not really need a lot of extra queries, it just needs to add some aggregations on the main query.
