### ISSUE TITLE
plugin installation failed - plugin-descriptor.properties missing in release tarball

### ISSUE THREAD

**Issue by kkaempf** [appbaseio/dejaVu#26]
Installing the 0.7.1 release tarball as a plugin fails with

> [2016-06-14 09:40:28,120][ERROR][bootstrap                ] Exception
> java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [dejaVu]. Was the plugin built before 2.0?

Installing `plugin-descriptor.properties` to `.../elasticsearch/plugins/dejaVu` fixes this.

Please add `plugin-descriptor.properties` to the release tarball on github.

**Comment by siddharthlatest** [comment]
@kkaempf the release is not for the chrome app, I recommend https://github.com/appbaseio/dejaVu/archive/master.zip for using the Elasticsearch plugin. We keep the `master` branch in sync as it's used by Elasticsearch for installation purposes.

**Comment by kkaempf** [comment]
Using the `v0.7.1-master` release fixes this.
