### ISSUE TITLE
Export as CSV does not apply filters

### ISSUE THREAD

**Issue by ryanwkan** [appbaseio/dejaVu#266]
Right now it is not passing in any `activeQuery`, so it exports the entire dataset. 

Is the feature being developed, or are you accepting contribution to get the feature working?

Thanks

@siddharthlatest

**Comment by siddharthlatest** [comment]
Hey @ryanwkan, we would love to accept contributions for this 💯. @lakhansamani can share a pointer on how you can implement this.

Ideally, the behavior should be something like this:
1. When no filters are selected, all data is selected to be exported.
2. When there are active search or facet filters, only the filtered data should be exported.

**Comment by lakhansamani** [comment]
Hey @ryanwkan,

With v3 we are using `ReactiveSearch` for querying and displaying result set, so we can take advantage of `onQueryChange` prop of `ReactiveList` for more information you can check https://opensource.appbase.io/reactive-manual/result-components/reactivelist.html#props

We can save `nextQuery` (without size and sort) in redux store and use it for exporting data.

Following are the components where you can add above changes

`ReactiveList` component in Dejavu: https://github.com/appbaseio/dejavu/blob/dev/app/src/components/DataBrowser/ResultSet.js

Export Component: https://github.com/appbaseio/dejavu/blob/dev/app/src/components/DataBrowser/ExportData.js

**Comment by ryanwkan** [comment]
Thanks @lakhansamani, @siddharthlatest ,

I'll work on this issue.

Ryan

**Comment by siddharthlatest** [comment]
Hey @ryanwkan, any updates on this?

**Comment by ryanwkan** [comment]
@siddharthlatest when's the expected timeline for 3.1.0? I'll get it ready for it

**Comment by siddharthlatest** [comment]
Hey @ryanwkan, we are looking to release it by next week.

**Comment by ryanwkan** [comment]
@siddharthlatest probably next milestone then. I'm looking at ~2 weeks
