### ISSUE TITLE
Export as CSV or JSON is causing duplicates

### ISSUE THREAD

**Issue by nmallya** [appbaseio/dejaVu#267]
Hi Support, 
I subscribed to a Bootstrap monthly plan. I am assuming the Browse Data tool in appbase.io is using Deja Vu

I am seeing the following serious issue:

Whenever I export my data in csv or json formats from the Browse Data screen, it ends up with the same record getting added 9 times. I have 9812 unique entries in my database but I end up with only a 1000 unique entries and the rest are duplicates.

I don't see any duplicates when I browse the data in your app. It just ends up in duplicates in the exported file. Could you please tell me why I am seeing this behavior?

**Comment by lakhansamani** [comment]
Hey @nmallya,

You are correct Browse Data tool in appbase dashboard uses Dejavu.

I was able to debug and replicate the above issue, it was mainly because of an error in export query, will be fixing it by today.

Thanks for reporting.

**Comment by lakhansamani** [comment]
Hey @nmallya,

Have fixed the above issue in #268 

Can you test, once with your index before we merge PR

Dejavu PR url: https://deploy-preview-268--inspiring-shockley-90e82f.netlify.com/?appname=&url=&mode=edit

Thanks

**Comment by nmallya** [comment]
Thank you @lakhansamani. It is working now.
