### ISSUE TITLE
site directory rename ?

### ISSUE THREAD

**Issue by kkaempf** [appbaseio/dejaVu#27]
Elasticsearch 2.3.3 fails to start with the dejaVu plugin:

> [2016-06-14 09:44:41,077][ERROR][bootstrap                ] Exception
> java.lang.IllegalArgumentException: Plugin [dejaVu] is a site plugin but has no '_site/' directory

dejaVu currently has a `site` directory. Changing this to `_site` lets elasticsearch start

**Comment by siddharthlatest** [comment]
@kkaempf I think this is related to your previous issue, you should either install dejavu from the master branch or use this zip https://github.com/appbaseio/dejaVu/archive/master.zip.

**Comment by kkaempf** [comment]
@siddharthlatest thanks, this zip seems to have everthing in place.

Can you make a new release please ? I'd like to package it as an rpm for openSUSE (see https://build.opensuse.org/package/show/security:logging/elasticsearch-dejaVu). And I need a version tag for this. `master` is not a valid version. ;-)

**Comment by siddharthlatest** [comment]
Does this work - https://github.com/appbaseio/dejaVu/releases/tag/v0.7.1-master?

**Comment by kkaempf** [comment]
Thanks, this works wonderfully.
