### ISSUE TITLE
Npm Compilation Problem

### ISSUE THREAD

**Issue by ltfi** [appbaseio/dejaVu#279]
![capture](https://user-images.githubusercontent.com/1550317/52716463-e1778700-2faf-11e9-9c81-66b250283b8b.PNG)
When I try to compile project source code encountered this error.

**Comment by lakhansamani** [comment]
Hey, @ltfi thanks for reporting, this is mainly because of version change in one of submodules, will be fixing it by today

**Comment by ltfi** [comment]
Thanks for quick response 👍

**Comment by lakhansamani** [comment]
@ltfi have just pushed version update for `batteries` submodule you can run

`git submodule update --recursive --remote` again on your local to sync with latest batteries version

**Comment by ltfi** [comment]
![image](https://user-images.githubusercontent.com/1550317/52770250-a030b700-3043-11e9-90c6-e4e428db9b08.png)

Still I'm getting these errors.
