### ISSUE TITLE
Exporting

### ISSUE THREAD

**Issue by zipzapduo** [appbaseio/dejaVu#281]
When i try to export to json i get undefined in the file contents

**Comment by lakhansamani** [comment]
@zipzapduo can you share, which version of Elasticsearch you are using.

Also, it would be great if you can share console/network error, that will help us debug better,
Thanks

**Comment by zipzapduo** [comment]
I am using from amazon service, i don't know for sure. The dejavu is in the chrome browser as an extension, how do i see the console?

**Comment by lakhansamani** [comment]
@zipzapduo thanks for the information, was able to replicate it.
Should be fixed by tomorrow 👍

**Comment by zipzapduo** [comment]
thank you

**Comment by lakhansamani** [comment]
@zipzapduo have added fix for exporting data on dejavu website, i.e. https://dejavu.appbase.io

Can you confirm there once if it works?
Thanks

**Comment by zipzapduo** [comment]
No. Its not working. I can send  a video to you

**Comment by lakhansamani** [comment]
@zipzapduo also getting the error from console can help us debug, you can open browser console by following instructions on https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by zipzapduo** [comment]
HTTP STATUS: 500 - Unable to get count. I sent you a video by your email

**Comment by lakhansamani** [comment]
Thank you @zipzapduo will debug and get back to you on this 👍

**Comment by lakhansamani** [comment]
@zipzapduo I have checked the video, you are testing on chrome extension, currently, we have fixed issue on dejavu website only.

Will update you once the new version of extension is available on store

**Comment by siddharthlatest** [comment]
This is out with the latest patch release.
