### ISSUE TITLE
Security posture of DejaVu developers.

### ISSUE THREAD

**Issue by MarlonBorba** [appbaseio/dejaVu#282]
Fellow GitHub'ers,

In order to approve use of DejaVu ElasticSearch Web UI for my employer, I need to get answers to some questions:

a) Where can I read about secure development practices used to create DejaVu?
b) Is there a page or site with security advisories and patches?
c) Were there reported vulnerabilities of DejaVu with CVSS >=7.0?

TIA,

Marlon.

**Comment by siddharthlatest** [comment]
@MarlonBorba Would your employer be interested in something like this? https://tidelift.com/subscription. We can potentially work with them to address the questions here if this seems worthwhile.

**Comment by MarlonBorba** [comment]
@siddharthlatest My question refers to the _security posture of DejaVu_ specifically. We could consider the Tidelift paid subscription _if_ and _when_ we adopt DejaVu.
Note that other OSS packages like Postman offer a detailed documentation about their security posture, even for free versions, q.v. https://www.getpostman.com/security
TIA,
Marlon.
