### ISSUE TITLE
Importer doesn't work to Elasticsearch Hosted running local instance of dejavu

### ISSUE THREAD

**Issue by mindis** [appbaseio/dejaVu#283]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)
Locally built `dev` branch of dejavu

#### What is the version of Dejavu that you are using?
dev version.

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

Can't import data using local instance of dejavu. Configure Data Mappings is inactive. Data browsing works fine.  Importing to appbase also works fine. No connection errors in browser console. 
![importer](https://user-images.githubusercontent.com/3082556/53587541-8bdfd480-3b82-11e9-8cc5-cf322092a9ba.png)

Also are you planning to make Importer app source code publicly available?

thanks!

**Comment by lakhansamani** [comment]
@mindis thanks for reporting this, I will test this
Can you share ES version that you are trying to import and also if you could share sample csv that will help us debug more

Thanks

**Comment by mindis** [comment]
ES 6.5.4

PUT 9200/index5

```
{
  "mappings": {
    "_doc": {
      "properties": {
        "my_field": {
          "type": "text"
        }
      }
    }
  }
}
```

test.csv:

```
id,my_field
1,london
2,paris
```

**Comment by mindis** [comment]
Hi @lakhansamani I wonder if you had a chance to look into this? Thanks!

**Comment by lakhansamani** [comment]
Hey @mindis I did not get chance to look into this, will surely try to replicate and fix this by end this week 👍

**Comment by lakhansamani** [comment]
@mindis I checked on the above issue.
Currently, we are supporting `.csv` import only with appbase apps / clusters. Please try to import `.json` file for local or any other cluster.

Also, `importer` will try to add mappings by itself. So in the app name field, try to use index name which is not on your cluster.
