### ISSUE TITLE
Field of type "annotated_text" is not searchable

### ISSUE THREAD

**Issue by mindis** [appbaseio/dejaVu#284]
I'm using locally built dejavu cloned from github repo with local elasticsearch.

I'm experimenting with new elasticsearch feature that allows to store and query annotated text https://www.elastic.co/guide/en/elasticsearch/plugins/6.6/mapper-annotated-text-usage.html

However fields of type "annotated_text" are not searchable in dejavu data browser and displayed with ellipsis (...)

How can I make "annotated_text" fields visible and searchable?

Many thanks!

**Comment by lakhansamani** [comment]
@mindis thank you for bringing this up,
Will add this in the upcoming release 👍

**Comment by lakhansamani** [comment]
@mindis I checked this, it is not part of default types, it available after installing a plugin, for any such special cases you can define your mappings, using `Add mapping` button.
