### ISSUE TITLE
Dejavu ES URL https

### ISSUE THREAD

**Issue by neilc2016** [appbaseio/dejaVu#286]
I've installed Dejavu and can connect to my test elastic cluster when the elastic URL is http unsecured.  However when I enable https on the elastic cluster Dejavu cannot connect via the https elastic URL.  The response shows that is having ERR_CERT_AUTHORITY_INVALID.  Is there a way to bypass the cert check on Dejavu?

**Comment by siddharthlatest** [comment]
@neilc2016 This isn't a Dejavu specific issue per se. Browsers would throw an error when connecting to a self-signed https cert. Try connecting outside of dejavu to your ES cluster, do you still see the error or not? 

Perhaps, this can help: https://superuser.com/questions/27268/how-do-i-disable-the-warning-chrome-gives-if-a-security-certificate-is-not-trust.

**Comment by neilc2016** [comment]
Thanks Siddharth.  I exported the elastic https URL cert and imported the cert back in Chrome.  Now when using Dejavu it can connect to the elastic https URL without the error.   All our logstash/Kibana/API services have disabled cert verification so we don't have to deal with this issue but will need to update cert for Dejavu.
