### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by edugrip** [appbaseio/dejaVu#294]
Can't install the application. 
Here is what I did. 
I am running Mac OSX Mojave.
 **~/ $ npm -v**
6.9.0
 **~/ $ node -v**
v10.15.2
**~/  $ yarn -v**
1.15.2
 

$ yarn install
$ npm start

> @appbaseio/dejavu@3.2.3 start /Users/rameshpareek/npm/dejavu
> NODE_ENV=development webpack-dev-server --open --mode development --content-base dist/app --history-api-fallback --hot --progress --colors --port 1358

clean-webpack-plugin: /Users/rameshpareek/npm/dejavu/dist/app has been removed.
 10% building modules 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:1358/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/rameshpareek/npm/dejavu/dist/app
ℹ ｢wds｣: 404s will fallback to /index.html
 10% building modules 1/3 modules 2 active .../node_modules/webpack/hot/dev-server.jsℹ ｢wdm｣: wait until bundle finished: /
✖ ｢wdm｣: Hash: 8b84db01a92fdb77aa96                                                         
Version: webpack 4.19.0
Time: 22809ms
Built at: 04/14/2019 10:37:29 AM
                                                      Asset       Size        Chunks             Chunk Names
                         importer/dist/fonts/ab-awesome.eot   13.6 KiB                [emitted]  
                         favicon/apple-touch-icon-57x57.png   2.42 KiB                [emitted]  
                         favicon/apple-touch-icon-72x72.png    3.2 KiB                [emitted]  
                         favicon/apple-touch-icon-76x76.png   3.42 KiB                [emitted]  
                       favicon/apple-touch-icon-114x114.png   5.39 KiB                [emitted]  
                       favicon/apple-touch-icon-120x120.png   5.69 KiB                [emitted]  
                       favicon/apple-touch-icon-144x144.png   7.15 KiB                [emitted]  
                       favicon/apple-touch-icon-152x152.png   7.55 KiB                [emitted]  
                       favicon/apple-touch-icon-167x167.png   8.51 KiB                [emitted]  
                       favicon/apple-touch-icon-180x180.png   9.28 KiB                [emitted]  
                               favicon/apple-touch-icon.png   9.28 KiB                [emitted]  
                   favicon/apple-touch-icon-precomposed.png   9.28 KiB                [emitted]  
                           favicon/android-chrome-36x36.png   1.05 KiB                [emitted]  
                           favicon/android-chrome-48x48.png   1.54 KiB                [emitted]  
                           favicon/android-chrome-72x72.png   2.51 KiB                [emitted]  
                           favicon/android-chrome-96x96.png   3.64 KiB                [emitted]  
                         favicon/android-chrome-144x144.png   5.68 KiB                [emitted]  
                         favicon/android-chrome-192x192.png   8.16 KiB                [emitted]  
                         favicon/android-chrome-256x256.png   11.8 KiB                [emitted]  
                         favicon/android-chrome-384x384.png   27.9 KiB                [emitted]  
                         favicon/android-chrome-512x512.png   43.2 KiB                [emitted]  
                                  favicon/favicon-16x16.png  420 bytes                [emitted]  
                                  favicon/favicon-32x32.png  940 bytes                [emitted]  
                                        favicon/favicon.ico   32.5 KiB                [emitted]  
              favicon/apple-touch-startup-image-320x460.png     23 KiB                [emitted]  
              favicon/apple-touch-startup-image-640x920.png   63.6 KiB                [emitted]  
             favicon/apple-touch-startup-image-640x1096.png   64.8 KiB                [emitted]  
             favicon/apple-touch-startup-image-748x1024.png   79.4 KiB                [emitted]  
             favicon/apple-touch-startup-image-750x1294.png   82.3 KiB                [emitted]  
             favicon/apple-touch-startup-image-768x1004.png   83.2 KiB                [emitted]  
            favicon/apple-touch-startup-image-1182x2208.png    162 KiB                [emitted]  
            favicon/apple-touch-startup-image-1242x2148.png    173 KiB                [emitted]  
            favicon/apple-touch-startup-image-1496x2048.png    226 KiB                [emitted]  
            favicon/apple-touch-startup-image-1536x2008.png    235 KiB                [emitted]  
                              favicon/firefox_app_60x60.png   4.27 KiB                [emitted]  
                            favicon/firefox_app_128x128.png   10.3 KiB                [emitted]  
                            favicon/firefox_app_512x512.png   67.1 KiB                [emitted]  
                                      favicon/manifest.json   1.19 KiB                [emitted]  
                                    favicon/manifest.webapp  260 bytes                [emitted]  
                                             favicon/.cache   5.19 KiB                [emitted]  
                       6509e6248b6ace10f42f2b1edb15df40.svg   2.79 KiB                [emitted]  
                       5418e9afa6a4ad673be4b41cf18d3230.svg   2.14 KiB                [emitted]  
                                                    main.js   2.08 MiB          main  [emitted]  main
                                            vendors~main.js    7.9 MiB  vendors~main  [emitted]  vendors~main
                                                 index.html   3.95 KiB                [emitted]  
                                                 _redirects   24 bytes                [emitted]  
                                              background.js  224 bytes                [emitted]  
                                              manifest.json  901 bytes                [emitted]  
                                                 popup.html  178 bytes                [emitted]  
                                                   popup.js  119 bytes                [emitted]  
                  importer/assets/images/AppbaseLogo@1x.png   5.53 KiB                [emitted]  
                         importer/assets/images/boolean.svg  530 bytes                [emitted]  
                         importer/assets/images/appbase.png   5.38 KiB                [emitted]  
                     importer/assets/images/dejavu_logo.png   2.61 KiB                [emitted]  
                     importer/assets/images/dejavu-logo.svg   2.79 KiB                [emitted]  
                          importer/assets/images/dejavu.png  835 bytes                [emitted]  
                            importer/assets/images/docs.png   3.15 KiB                [emitted]  
           importer/assets/images/Elasticsearch_Logo@1x.png   5.24 KiB                [emitted]  
                   importer/assets/images/elasticsearch.svg   3.42 KiB                [emitted]  
                         importer/assets/images/favicon.ico   1.12 KiB                [emitted]  
                           importer/assets/images/float.svg   1.33 KiB                [emitted]  
                       importer/assets/images/Group5@1x.png   1.52 KiB                [emitted]  
                       importer/assets/images/Group5@2x.png   3.46 KiB                [emitted]  
                        importer/assets/images/inbox@2x.png   1.25 KiB                [emitted]  
                        importer/assets/images/inbox@1x.png  661 bytes                [emitted]  
                      importer/assets/images/logo-white.svg   3.25 KiB                [emitted]  
                         importer/assets/images/keyword.svg  773 bytes                [emitted]  
                            importer/assets/images/logo.svg   3.25 KiB                [emitted]  
                          importer/assets/images/string.svg  433 bytes                [emitted]  
                               importer/dist/css/custom.css   75 bytes                [emitted]  
                                importer/dist/css/fonts.css    5.8 KiB                [emitted]  
      importer/dist/js/6509e6248b6ace10f42f2b1edb15df40.svg   2.79 KiB                [emitted]  
                     importer/assets/images/AppbaseLogo.png   13.3 KiB                [emitted]  
                          importer/assets/images/banner.png   9.61 KiB                [emitted]  
                       importer/assets/images/dashboard.jpg   14.2 KiB                [emitted]  
              importer/assets/images/Elasticsearch_Logo.png   11.1 KiB                [emitted]  
                            importer/assets/images/json.png   8.12 KiB                [emitted]  
                         importer/dist/fonts/ab-awesome.ttf   13.4 KiB                [emitted]  
                         favicon/apple-touch-icon-60x60.png   2.58 KiB                [emitted]  
                        importer/dist/fonts/ab-awesome.woff    8.6 KiB                [emitted]  
                            importer/dist/images/banner.png   9.61 KiB                [emitted]  
                         importer/assets/images/userImg.png   16.6 KiB                [emitted]  
                         importer/dist/fonts/ab-awesome.svg   19.1 KiB                [emitted]  
      importer/dist/js/347fdca475f1d401e94512f035baad21.png   9.61 KiB                [emitted]  
       importer/dist/fonts/glyphicons-halflings-regular.eot   19.7 KiB                [emitted]  
      importer/dist/fonts/glyphicons-halflings-regular.woff   22.9 KiB                [emitted]  
     importer/dist/fonts/glyphicons-halflings-regular.woff2   17.6 KiB                [emitted]  
       importer/dist/fonts/source/sourcesanspro-black.woff2   22.1 KiB                [emitted]  
     importer/dist/fonts/source/sourcesanspro-blackit.woff2   22.6 KiB                [emitted]  
        importer/dist/fonts/source/sourcesanspro-bold.woff2   23.2 KiB                [emitted]  
      importer/dist/fonts/source/sourcesanspro-boldit.woff2   23.5 KiB                [emitted]  
  importer/dist/fonts/source/sourcesanspro-extralight.woff2   22.5 KiB                [emitted]  
importer/dist/fonts/source/sourcesanspro-extralightit.woff2   23.6 KiB                [emitted]  
       importer/dist/fonts/source/sourcesanspro-light.woff2   23.1 KiB                [emitted]  
     importer/dist/fonts/source/sourcesanspro-regular.woff2   23.5 KiB                [emitted]  
    importer/dist/fonts/source/sourcesanspro-semibold.woff2   23.6 KiB                [emitted]  
  importer/dist/fonts/source/sourcesanspro-semiboldit.woff2   23.5 KiB                [emitted]  
                             importer/assets/images/csv.png   24.3 KiB                [emitted]  
                   importer/assets/images/elasticsearch.png   26.5 KiB                [emitted]  
                                  importer/dist/css/csv.png   24.3 KiB                [emitted]  
         importer/dist/fonts/source/sourcesanspro-black.eot   25.1 KiB                [emitted]  
        importer/dist/fonts/source/sourcesanspro-black.woff   28.4 KiB                [emitted]  
       importer/dist/fonts/source/sourcesanspro-blackit.eot   25.9 KiB                [emitted]  
      importer/dist/fonts/source/sourcesanspro-blackit.woff   29.3 KiB                [emitted]  
        importer/dist/fonts/source/sourcesanspro-boldit.eot   26.7 KiB                [emitted]  
       importer/dist/fonts/source/sourcesanspro-boldit.woff   30.2 KiB                [emitted]  
          importer/dist/fonts/source/sourcesanspro-bold.eot   26.5 KiB                [emitted]  
    importer/dist/fonts/source/sourcesanspro-extralight.eot   25.6 KiB                [emitted]  
   importer/dist/fonts/source/sourcesanspro-extralight.woff   28.7 KiB                [emitted]  
 importer/dist/fonts/source/sourcesanspro-extralightit.woff   30.2 KiB                [emitted]  
         importer/dist/fonts/source/sourcesanspro-bold.woff   29.6 KiB                [emitted]  
  importer/dist/fonts/source/sourcesanspro-extralightit.eot   26.8 KiB                [emitted]  
           importer/dist/fonts/source/sourcesanspro-it.woff   30.6 KiB                [emitted]  
          importer/dist/fonts/source/sourcesanspro-it.woff2     24 KiB                [emitted]  
         importer/dist/fonts/source/sourcesanspro-light.eot   26.3 KiB                [emitted]  
            importer/dist/fonts/source/sourcesanspro-it.eot   27.2 KiB                [emitted]  
        importer/dist/fonts/source/sourcesanspro-light.woff   29.4 KiB                [emitted]  
      importer/dist/fonts/source/sourcesanspro-lightit.woff   30.9 KiB                [emitted]  
       importer/dist/fonts/source/sourcesanspro-regular.eot   26.7 KiB                [emitted]  
     importer/dist/fonts/source/sourcesanspro-lightit.woff2   24.2 KiB                [emitted]  
      importer/dist/fonts/source/sourcesanspro-regular.woff   29.9 KiB                [emitted]  
     importer/dist/fonts/source/sourcesanspro-semibold.woff   30.1 KiB                [emitted]  
    importer/dist/fonts/source/sourcesanspro-semiboldit.eot   26.6 KiB                [emitted]  
       importer/dist/fonts/source/sourcesanspro-lightit.eot   27.5 KiB                [emitted]  
      importer/dist/fonts/source/sourcesanspro-semibold.eot   26.9 KiB                [emitted]  
   importer/dist/fonts/source/sourcesanspro-semiboldit.woff   30.1 KiB                [emitted]  
                            importer/dist/css/style.min.css   39.9 KiB                [emitted]  
                           importer/dist/js/arrayParsing.js  950 bytes                [emitted]  
                            importer/dist/vendor/JSONURL.js   57 bytes                [emitted]  
                                        importer/index.html   4.43 KiB                [emitted]  
       importer/dist/fonts/glyphicons-halflings-regular.ttf   44.3 KiB                [emitted]  
                importer/dist/fonts/fontawesome-webfont.eot   54.7 KiB                [emitted]  
                      importer/dist/vendor/papaparse.min.js   18.4 KiB                [emitted]  
               importer/dist/fonts/fontawesome-webfont.woff   63.9 KiB                [emitted]  
         importer/dist/fonts/source/sourcesanspro-black.ttf   63.7 KiB                [emitted]  
       importer/dist/fonts/source/sourcesanspro-blackit.ttf   62.3 KiB                [emitted]  
        importer/dist/fonts/source/sourcesanspro-boldit.ttf   62.7 KiB                [emitted]  
            importer/dist/fonts/source/sourcesanspro-it.ttf   63.7 KiB                [emitted]  
    importer/dist/fonts/source/sourcesanspro-semiboldit.ttf   63.3 KiB                [emitted]  
          importer/dist/fonts/source/sourcesanspro-bold.ttf   64.5 KiB                [emitted]  
    importer/dist/fonts/source/sourcesanspro-extralight.ttf   65.2 KiB                [emitted]  
  importer/dist/fonts/source/sourcesanspro-extralightit.ttf   66.2 KiB                [emitted]  
         importer/dist/fonts/source/sourcesanspro-light.ttf   65.2 KiB                [emitted]  
       importer/dist/fonts/source/sourcesanspro-lightit.ttf   65.8 KiB                [emitted]  
       importer/dist/fonts/source/sourcesanspro-regular.ttf   65.5 KiB                [emitted]  
      importer/dist/fonts/source/sourcesanspro-semibold.ttf   65.4 KiB                [emitted]  
              importer/dist/fonts/fontawesome-webfont.woff2   75.4 KiB                [emitted]  
                        importer/dist/fonts/FontAwesome.otf   83.9 KiB                [emitted]  
                             importer/dist/js/validateId.js   71.6 KiB                [emitted]  
       importer/dist/fonts/glyphicons-halflings-regular.svg    106 KiB                [emitted]  
                importer/dist/fonts/fontawesome-webfont.ttf    110 KiB                [emitted]  
                        importer/dist/vendor/lzma_worker.js    109 KiB                [emitted]  
                           importer/dist/css/vendor.min.css    158 KiB                [emitted]  
                             importer/dist/js/vendor.min.js    159 KiB                [emitted]  
                importer/dist/fonts/fontawesome-webfont.svg    280 KiB                [emitted]  
                    importer/dist/css/bootstrap.min.css.map    529 KiB                [emitted]  
                                    importer/dist/js/app.js   3.22 MiB                [emitted]  
Entrypoint main = vendors~main.js main.js
[./app/src/App.js] 64.9 KiB {main} [built]
[./app/src/index.js] 391 bytes {main} [built]
[./node_modules/cross-storage/lib/index.js] 110 bytes {vendors~main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {vendors~main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {vendors~main} [built]
[./node_modules/react/index.js] 190 bytes {vendors~main} [built]
[0] multi (webpack)-dev-server/client?http://localhost:1358 (webpack)/hot/dev-server.js ./app/src/index.js 52 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {vendors~main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:1358] (webpack)-dev-server/client?http://localhost:1358 7.78 KiB {vendors~main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {vendors~main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {vendors~main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 KiB {vendors~main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {vendors~main} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {vendors~main} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.11 KiB {vendors~main} [built]
    + 1248 hidden modules

ERROR in ./app/src/components/SearchPreview.js
Module not found: Error: Can't resolve '../batteries/components/BaseContainer' in '/Users/rameshpareek/npm/dejavu/app/src/components'
 @ ./app/src/components/SearchPreview.js 6:0-66 20:166-179
 @ ./app/src/App.js
 @ ./app/src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1358 (webpack)/hot/dev-server.js ./app/src/index.js

ERROR in ./app/src/components/SearchPreview.js
Module not found: Error: Can't resolve '../batteries/components/SearchSandbox' in '/Users/rameshpareek/npm/dejavu/app/src/components'
 @ ./app/src/components/SearchPreview.js 5:0-66 25:25-38
 @ ./app/src/App.js
 @ ./app/src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1358 (webpack)/hot/dev-server.js ./app/src/index.js

ERROR in ./app/src/components/SearchPreview.js
Module not found: Error: Can't resolve '../batteries/components/SearchSandbox/containers/Editor' in '/Users/rameshpareek/npm/dejavu/app/src/components'
 @ ./app/src/components/SearchPreview.js 7:0-77 29:25-31
 @ ./app/src/App.js
 @ ./app/src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1358 (webpack)/hot/dev-server.js ./app/src/index.js

ERROR in ./app/src/reducers/index.js
Module not found: Error: Can't resolve '../batteries/modules/reducers' in '/Users/rameshpareek/npm/dejavu/app/src/reducers'
 @ ./app/src/reducers/index.js 21:0-62 45:3-20
 @ ./app/src/store/index.js
 @ ./app/src/App.js
 @ ./app/src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1358 (webpack)/hot/dev-server.js ./app/src/index.js
Child favicons-webpack-plugin for "iconstats-[hash].json":
                                              Asset       Size  Chunks             Chunk Names
                 favicon/android-chrome-512x512.png   43.2 KiB          [emitted]  
                 favicon/apple-touch-icon-57x57.png   2.42 KiB          [emitted]  
                 favicon/apple-touch-icon-72x72.png    3.2 KiB          [emitted]  
                 favicon/apple-touch-icon-76x76.png   3.42 KiB          [emitted]  
               favicon/apple-touch-icon-114x114.png   5.39 KiB          [emitted]  
               favicon/apple-touch-icon-120x120.png   5.69 KiB          [emitted]  
               favicon/apple-touch-icon-144x144.png   7.15 KiB          [emitted]  
               favicon/apple-touch-icon-152x152.png   7.55 KiB          [emitted]  
               favicon/apple-touch-icon-167x167.png   8.51 KiB          [emitted]  
               favicon/apple-touch-icon-180x180.png   9.28 KiB          [emitted]  
                       favicon/apple-touch-icon.png   9.28 KiB          [emitted]  
           favicon/apple-touch-icon-precomposed.png   9.28 KiB          [emitted]  
                   favicon/android-chrome-36x36.png   1.05 KiB          [emitted]  
                   favicon/android-chrome-48x48.png   1.54 KiB          [emitted]  
                   favicon/android-chrome-72x72.png   2.51 KiB          [emitted]  
                   favicon/android-chrome-96x96.png   3.64 KiB          [emitted]  
                 favicon/android-chrome-144x144.png   5.68 KiB          [emitted]  
                 favicon/android-chrome-192x192.png   8.16 KiB          [emitted]  
                 favicon/android-chrome-256x256.png   11.8 KiB          [emitted]  
                 favicon/android-chrome-384x384.png   27.9 KiB          [emitted]  
                 favicon/apple-touch-icon-60x60.png   2.58 KiB          [emitted]  
                          favicon/favicon-16x16.png  420 bytes          [emitted]  
                          favicon/favicon-32x32.png  940 bytes          [emitted]  
                                favicon/favicon.ico   32.5 KiB          [emitted]  
      favicon/apple-touch-startup-image-320x460.png     23 KiB          [emitted]  
      favicon/apple-touch-startup-image-640x920.png   63.6 KiB          [emitted]  
     favicon/apple-touch-startup-image-640x1096.png   64.8 KiB          [emitted]  
     favicon/apple-touch-startup-image-748x1024.png   79.4 KiB          [emitted]  
     favicon/apple-touch-startup-image-750x1294.png   82.3 KiB          [emitted]  
     favicon/apple-touch-startup-image-768x1004.png   83.2 KiB          [emitted]  
    favicon/apple-touch-startup-image-1182x2208.png    162 KiB          [emitted]  
    favicon/apple-touch-startup-image-1242x2148.png    173 KiB          [emitted]  
    favicon/apple-touch-startup-image-1496x2048.png    226 KiB          [emitted]  
    favicon/apple-touch-startup-image-1536x2008.png    235 KiB          [emitted]  
                      favicon/firefox_app_60x60.png   4.27 KiB          [emitted]  
                    favicon/firefox_app_128x128.png   10.3 KiB          [emitted]  
                    favicon/firefox_app_512x512.png   67.1 KiB          [emitted]  
                              favicon/manifest.json   1.19 KiB          [emitted]  
                            favicon/manifest.webapp  260 bytes          [emitted]  
                                     favicon/.cache   5.19 KiB          [emitted]  
     + 1 hidden asset
    Entrypoint undefined = iconstats-5c37bcb2c2ff1f52dd09.json
    [./node_modules/favicons-webpack-plugin/lib/favicons.js?{"outputFilePrefix":"favicon/","icons":{"android":true,"appleIcon":true,"appleStartup":true,"coast":false,"favicons":true,"firefox":true,"opengraph":false,"twitter":false,"yandex":false,"windows":false},"background":"#fff","persistentCache":true,"appName":"@appbaseio/dejavu"}!./app/src/favicon/favicon.png] 5.09 KiB {0} [built]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html] 738 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

**Comment by lakhansamani** [comment]
@edugrip seems like you have missed out on step 2, mentioned in docs.
i.e. adding `batteries` as git sub-module

https://github.com/appbaseio/dejavu/blob/dev/CONTRIBUTING.md
