### ISSUE TITLE
unable to supoort elasticsearch 7.0.0

### ISSUE THREAD

**Issue by heavenkiller2018** [appbaseio/dejaVu#295]
unable to supoort elasticsearch 7.0.0

**Comment by siddharthlatest** [comment]
Most likely, the mapping API will be the breaking change as the `type` info is omitted in the ES response now.

@heavenkiller2018 Are you seeing any other issue?

**Comment by lakhansamani** [comment]
Fixed here https://github.com/appbaseio/dejavu/commit/b504c0f8720e556dd173dd5385e3815eaa1bb9da
