### ISSUE TITLE
Import does not work in Elastic 5

### ISSUE THREAD

**Issue by ghost** [appbaseio/dejaVu#297]
I am using a Chrome extension to access my custom ES cluster, however, the import fails. I am seeing an error message:

```
{"error":{"readyState":4,"responseText":"","status":403,"statusText":"Forbidden"},"endpoint":"_close"}
```

I am trying to create a new index, so I specify a new index name in the app name. I am using superadmin credentials so I have wildcard access to everything.

This problem happens in Elasticsearch 5. Elasticsearch 6 is just fine.

**Comment by siddharthlatest** [comment]
@dealancer This is an issue with your ES hosting provider, which doesn't allow using the `/_close` endpoint.

**Comment by ghost** [comment]
@siddharthlatest is there a way to enable such capability? I am not using any specific ES hosting provider, just a custom installation.

**Comment by siddharthlatest** [comment]
> {"error":{"readyState":4,"responseText":"","status":403,"statusText":"Forbidden"},"endpoint":"_close"}

This error essentially says calling the `/_close` endpoint returned a 403. You can check if you have anything on your backend routes that prevents this particular endpoint from getting called. For e.g. AWS ES blocks the `/_close` endpoint. It works for a general ElasticSearch cluster.
