### ISSUE TITLE
Add a checkbox not to verify a certificate

### ISSUE THREAD

**Issue by ghost** [appbaseio/dejaVu#299]
My ES cluster is a temporary one and does not have a valid certificate. I am seeing an error message:

```
app.js?v=1:34 GET https://example.com:9200/_cluster/state net::ERR_CERT_AUTHORITY_INVALID
```

The workaround is to access https://example.com:9200 from another browser window and click proceed button. Is there a way to make skipping SSL cert check in a more user-friendly way, e.g. checkbox?

**Comment by lakhansamani** [comment]
This issue is more related to certification for Elasticsearch cluster. Elasticsearch `curl`/`API` can only work if the authorized connection string is provided.

**Comment by ghost** [comment]
I found two workarounds for this:

1. Open direction connection to Elastic in the separate window and allow the cert
2. Add a cert to the trust store locally
