### ISSUE TITLE
The README.md doesn't say how to access it once the plugin is installed

### ISSUE THREAD

**Issue by LeeDr** [appbaseio/dejaVu#3]
The README.md tells how to install the plugin, and what elasticsearch configuration is needed, but not how to access it once it's installed (or I'm missing it)

**Comment by lakshgupta** [comment]
+1

**Comment by farhan687** [comment]
FIxed in https://github.com/appbaseio/dejaVu/commit/211e2ac43d128360c9aa6279ef16dbced33536e3.

**Comment by LeeDr** [comment]
LGTM - not sure if you want the originator to close?
