### ISSUE TITLE
Query browser does not work

### ISSUE THREAD

**Issue by ghost** [appbaseio/dejaVu#301]
Dejavu (Chrome extension) hangs when trying to connect to ES5 and ES6. Following messages appear in the console:

```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
build.min.js:1 {url: "https://admin:password@example.com:9200", appname: "index", username: "", password: "", host: ""} {username: "admin", password: "password", url: "https://example.com:9200"}
build.min.js:8 setting up appbase
build.min.js:8 https://example.com:9200/index/_settings?human
build.min.js:8 https://example.com:9200/index/_mapping/
```

**Comment by lakhansamani** [comment]
Are you trying to access importer/query explorer?

**Comment by ghost** [comment]
@lakhansamani  Query explorer.

**Comment by lakhansamani** [comment]
@dealancer seems like QueryExplorer is not able to connect to "https://example.com:9200"

If you are having certificate issue then it might not work as elasticsearch API needs authorized URL. If it is a local cluster that you are not able to connect then probably you can try using QueryExplorer chrome extension. https://chrome.google.com/webstore/detail/mirage/dcnlpfmnpoggchflmdnkgiepijgljoka?hl=en
