### ISSUE TITLE
Dejavu - Chrome Plugin - Compatibility with ElasticSearch 7.0.1

### ISSUE THREAD

**Issue by karthikeyank8** [appbaseio/dejaVu#307]
We upgraded from ES 6.6.1 to ES 7.0.1 by taking a snapshot of the ES 6.6.1 and upgraded to ES 7.0.1. After the upgrade we are able to connect to the ES 7.0.1 but the values is index is not displayed as a table in Data Browser and shows up as one single object.

This makes the nice features of Dejavu like search, sort, etc cannot be used. I have attached the snapshots of the index display in both the versions for your reference.

[ES_Screenshots.docx](https://github.com/appbaseio/dejavu/files/3158502/ES_Screenshots.docx)

**Comment by tlkristensen** [comment]
I am seeing the same behavior when connecting to elasticsearch running on the cloud offering from Elastic?! 

Do anyone have any suggestions?

**Comment by chigix** [comment]
This problem occurs in server edition of Dejavu as well. Mainly because of [removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/removal-of-types.html), property mappings defined in types previously could not work with Elasticsearch after version 7

**Comment by karthikeyank8** [comment]
Does that mean a new index created in Elastic Search 7 will work the way it used to be?

And the the index migrated migrated from earlier versions will have this problem which will not be fixed in near future?

**Comment by chigix** [comment]
No, API response has changed for this breaking change, which means that the response will not be the same structure as it used to be. Though [a deprecated option](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/removal-of-types.html#_indices_apis)could make working around, but that option is not suggested and not seems supported by dejavu as well

**Comment by lakhansamani** [comment]
@chigix the api response for mappings has changed for v7, so we tried fixing that here https://dejavu.appbase.io
Will be updating chrome extension soon.

Let us know if you are still facing this issue, should be a quick resolve. Also if you can share more insights on what is the exact error that you are getting, in the developer console, then that would help us debug more.

Thanks.

**Comment by chigix** [comment]
Fields typed as `date` does not work in the latest version when working with V7:
![image](https://user-images.githubusercontent.com/2692787/58405100-a05c3c00-80a1-11e9-9a6e-bd78edb3bd20.png)

I've checked the http request logs in browser and confirmed that the mapping of the index has been fetched correctly including correct date typing information in it:

![image](https://user-images.githubusercontent.com/2692787/58405249-f29d5d00-80a1-11e9-90d5-ccb4bc727e2f.png)

But I'm not sure whether this is the problem for the api change since V7 or the bug of date picker plugin historically.

**Comment by lakhansamani** [comment]
@chigix thanks for reporting this, currently we are not supporting date field with multiple formats, Will try to fix this with next release.

**Comment by lakhansamani** [comment]
@chigix thanks for reporting it. it is fixed here https://github.com/appbaseio/dejavu/commit/92ac8df1bfe3a22aad51527090ec6c65e58545aa

And is available with the latest release
https://github.com/appbaseio/dejavu/releases/tag/3.3.0
