### ISSUE TITLE
Can't connect to elasticsearch cluster in docker swarm

### ISSUE THREAD

**Issue by SilentCC** [appbaseio/dejaVu#308]
I deploy a elasticsearch cluster in docker swarm.Containers can find elasticsearch service with container's name. For example, I can access elasticsearch cluster with command: curl http://es_client:9200  in a dejavu container which deployed on the same docker swarm service as elasticsearch cluster  , and it works fine. I don't need to set cros in my elasticsearch cluster.

But when I used http://es_client:9200 and * to match indices ,it can't connect elasticsearch service.

**Comment by siddharthlatest** [comment]
@SilentCC CORS restriction is browser specific, which is why you are seeing it when running Dejavu in a browser. Dejavu doesn't run a server - that was a design decision we made to make it easy to install for users.

Hope this helps.
