### ISSUE TITLE
blank pages after clicking on Import Data

### ISSUE THREAD

**Issue by ghost** [appbaseio/dejaVu#314]
in the UI, clicking on "Import Data" in the left pane shows me a page "
GUI for importing CSV and JSON data into appbase.io / Elasticsearch" which is ok.

However, from there when I click on "Data Browser" or "Query Explorer" or "Search Preview" I get blank pages forever.

Installed from Docker, tested on Safari, Mac

When I avoid clicking the "Import Data" link all is fine

**Comment by lakhansamani** [comment]
@pouledodue thanks for reporting this, will look into it 👍
