### ISSUE TITLE
Update utility doesn't work

### ISSUE THREAD

**Issue by KarmeleJisc** [appbaseio/dejaVu#32]
Update data window is not working anymore, I used this before and it worked properly. 
Now 'Update' button from Update Data window doesn't do anything

**Comment by siddharthlatest** [comment]
@KarmeleJisc are you using it as an Elasticsearch plugin, via chrome app or the hosted gh-pages?

**Comment by KarmeleJisc** [comment]
Elasticsearch plugin via chrome app

**Comment by siddharthlatest** [comment]
@KarmeleJisc confirming the issue, thanks for reporting

**Comment by siddharthlatest** [comment]
@KarmeleJisc this has been fixed in ``v0.7.3`` release, now available on the chrome store - https://chrome.google.com/webstore/detail/dejavu/lcanobbdndljimodckphgdmllahfcadd?hl=en
