### ISSUE TITLE
Wildcard not supported for index name?

### ISSUE THREAD

**Issue by javadevmtl** [appbaseio/dejaVu#320]
Hi using the latest docker image...

appbaseio/dejavu

When I put an index name like: myindex-* it just keeps trying to connect.

**Comment by lakhansamani** [comment]
@javadevmtl not able to replicate the above issue. Seems like it must be a connection issue, where docker is not having access to that network.

closing this issue, for now, feel free to re-open it with more details about the ES version and your setup.

**Comment by siddharthlatest** [comment]
@lakhansamani I am seeing this issue with v7 ElasticSearch.

Edit: No, it was an unrelated issue.

**Comment by javadevmtl** [comment]
Sorry, late reply. I just got back to this... And also wasn't clear enough...

I'm running appbaseio/dejavu:latest on a docker image.

I am able to connect and I can even browse no problem...

But the moment you specify an index name **with a wildcard * for example some-index-*** It does not connect. If I put the full index name it works no problem.

**Comment by javadevmtl** [comment]
Also forgot to mention. Running: Elastic 6.4.2

1- So I connected to single index: my-index-2019.09 Works perfect.
2- Hit disconect.
3- Change name of index to: my-index-*
4- Connection blue bar animates for ever.

I did a browser debug. It may be stuck at getting the mapping for multiple indexes?

It tried these steps...
- search: http://xxxxxx/my-index-2019.09/_search?from=0&size=0 200 OK
- settings: http://xxxxxx/my-index-2019.09/_settings 200 OK
- Test the ES node: http://xxxxxx/ 200 OK
- Mapping: http://xxxxxx/my-index-*/_mapping 200 OK
- Mapping: http://xxxxxx/my-index-*/_mapping 200 OK
- Mapping: http://xxxxxx/my-index-*/_mapping 200 OK
- Mapping: http://xxxxxx/my-index-*/_mapping 200 OK
- Mapping: http://xxxxxx/my-index-*/_mapping 200 OK

They all succeeded with 200 OK, but it tried to map 5 times and it stuck.

**Comment by lakhansamani** [comment]
@javadevmtl I tried following the similar process with latest Dejavu docker image and ElasticSearch 6.4.2. Where I tried connecting to multiple indexes using wild-card and it worked perfectly for me.
