### ISSUE TITLE
Cannot connect using username and password

### ISSUE THREAD

**Issue by josh-axy** [appbaseio/dejaVu#325]
I can't connect to ES using my username and password when `xpack.security.enabled` is set to true.

My **URL format** in `dejavu` is like: `https://username:password@my.domain.com:9200`

My **index**: `*`

### My result:

![360截图20190727160114102](https://user-images.githubusercontent.com/7274196/61991807-225be780-b088-11e9-972f-373f8c58b577.jpg)

I can connect to ES in **Postman** manually using `https://username:password@my.domain.com:9200`

**Comment by abrantes01** [comment]
Hello @cosloli , did you find any solutions ?

**Comment by yx-hh** [comment]
I can do it! 
My URL format in dejavu is like: https://username:password@my.domain.com:9200

**Comment by lakhansamani** [comment]
@EstellaHuang can you share console error here, that would help in debugging the issue.

**Comment by yx-hh** [comment]
@lakhansamani when I type https://username:password@my.domain.com:9200 and index, choose connect, I can get my ES data without any error. So I think in this way, it works. My ES version 7.7.0 with enabled Xpack and SSL.

**Comment by katatohuk** [comment]
Is that neccessary to use https ? I cant get it working with http :(

**Comment by yx-hh** [comment]
> Is that neccessary to use https ? I cant get it working with http :(

@katatohuk No need to use https, http is ok too, you should check if there are some special character in your username or password, so it can't connect, such as '@'

**Comment by katatohuk** [comment]
> > Is that neccessary to use https ? I cant get it working with http :(
> 
> @katatohuk No need to use https, http is ok too, you should check if there are some special character in your username or password, so it can't connect, such as '@'

Right, I already figured out that it's not neccessary to use https, but the weird thing I still can't connecto to ES from dejavu
Maybe there is a way to get a more verbose output while connecting ?
I'm trying to connect to my cluster as http://elastic:PaSSw0rd@10.205.25.101:9200
I tested the connection from the different places and it works, used both commands:
```
curl http://elastic:PaSSw0rd@10.205.25.101:9200
curl -XGET -u elastic:PaSSw0rd http://10.205.25.101:9200
```
xpack and cors enabled
Any ideas why it doesn't work ? Thanks

**Comment by yx-hh** [comment]
my configuration in ‘elasticsearch.yml’ as follow
```
cluster.name: "docker-cluster"
network.host: 0.0.0.0
xpack.security.enabled: true
xpack.license.self_generated.type: basic
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12

http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: Authorization,X-Requested-With,Content-Length,Content-Type
```
Can you find out any difference?

**Comment by katatohuk** [comment]
> my configuration in ‘elasticsearch.yml’ as follow
> 
> ```
> cluster.name: "docker-cluster"
> network.host: 0.0.0.0
> xpack.security.enabled: true
> xpack.license.self_generated.type: basic
> xpack.security.transport.ssl.enabled: true
> xpack.security.transport.ssl.verification_mode: certificate
> xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
> xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
> 
> http.cors.enabled: true
> http.cors.allow-origin: "*"
> http.cors.allow-headers: Authorization,X-Requested-With,Content-Length,Content-Type
> ```
> 
> Can you find out any difference?

which version of ES are you using ?

**Comment by katatohuk** [comment]
> > my configuration in ‘elasticsearch.yml’ as follow
> > ```
> > cluster.name: "docker-cluster"
> > network.host: 0.0.0.0
> > xpack.security.enabled: true
> > xpack.license.self_generated.type: basic
> > xpack.security.transport.ssl.enabled: true
> > xpack.security.transport.ssl.verification_mode: certificate
> > xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
> > xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
> > 
> > http.cors.enabled: true
> > http.cors.allow-origin: "*"
> > http.cors.allow-headers: Authorization,X-Requested-With,Content-Length,Content-Type
> > ```
> > 
> > 
> > Can you find out any difference?
> 
Mine is as follows:
```
cluster.name: "errorlogs-elasticsearch-cluster"
    network.host: 0.0.0.0
    http.port: 9200
    http.cors.allow-origin: "*"
    http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
    http.cors.allow-credentials: true
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true

```

**Comment by yx-hh** [comment]
@katatohuk  elasticsearch:6.8.3

**Comment by katatohuk** [comment]
> @katatohuk elasticsearch:6.8.3

Weird, tried different versions already, still can't connect, now using oss ES version, turned off autorization. Dejavu is running as a container in k8s cluster, able to curl/wget elasticsearch internal name/IP address, but from UI doesn't work :(

**Comment by yx-hh** [comment]
> > @katatohuk elasticsearch:6.8.3
> 
> Weird, tried different versions already, still can't connect, now using oss ES version, turned off autorization. Dejavu is running as a container in k8s cluster, able to curl/wget elasticsearch internal name/IP address, but from UI doesn't work :(

maybe it's something wrong with your dejavu. My dejavu is running as a container but not in k8s cluster.

**Comment by lakhansamani** [comment]
@EstellaHuang we have released new version 3.4.7 of Dejavu yesterday, which fixes issue with basic auth login.

Can your try that and let us know if that works or issue still continues.

**Comment by yx-hh** [comment]
@lakhansamani the new version also works for me.

**Comment by lakhansamani** [comment]
Awesome, closing this issue now
