### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by consult-kk** [appbaseio/dejaVu#327]
Does this even work ?
I have ES 2.4.6 running as a docker image.
I started the docker image for the UI and when I try "http://localhost:9200" and provide the index name , it keeps saying some weird Network error.

**Comment by siddharthlatest** [comment]
@consult-kk Have you applied the CORS settings to ES?

**Comment by venttola** [comment]
You need to prepend the connection url with http:// or you'll get a network issue "You are trying to load http content over https. You might have to enable mixed content of your browser https://kb.iu.edu/d/bdny"
