### ISSUE TITLE
Some missing information

### ISSUE THREAD

**Issue by dmaj** [appbaseio/dejaVu#334]
As I see it, the description for starting Elasticsearch is not complete. CORS missing: "http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE".

`docker run --name es -d -p 9200:9200 -e http.port=9200 -e http.cors.enabled=true -e http.cors.allow-origin="*" -e http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE -e http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -e http.cors.allow-credentials=true docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2`

For a quick test with Docker, as shown in the GUI, you might want to note that you need to create an index first (curl -XPUT http://localhost:9200/myindex). 

And for people who start to despair of CORS, the hint that origin also knows a wildcart can help. http.cors.allow-origin="*". This is totally insecure as it allows connections from anywhere, but often helpful in despair. Just don't forget to undo it again.

**Comment by siddharthlatest** [comment]
@dmaj The methods are already defaulting to those, they don't need to be set explicitly. Other things you say are true, but we say them right on the home page.

Ref:

![](https://i.imgur.com/ppZvrbQ.png)
