### ISSUE TITLE
Booleans displaying in Dejavu UI - after modifying and scrolling the old value is displayed, but data is modified

### ISSUE THREAD

**Issue by liubhub** [appbaseio/dejaVu#338]
Say I modify the first value to `true`:
![Screenshot from 2019-09-20 10-16-04](https://user-images.githubusercontent.com/39431745/65307196-f2b0f380-db8f-11e9-9f04-97f73d979ebe.png)
like this

![Screenshot from 2019-09-20 10-19-33](https://user-images.githubusercontent.com/39431745/65307391-5509f400-db90-11e9-9907-53bc44b4b82e.png)

And using this scroll at the bottom, scroll it to the  left, and then return back
![Screenshot from 2019-09-20 10-16-44](https://user-images.githubusercontent.com/39431745/65307198-f47ab700-db8f-11e9-948b-2eb0011b431e.png)

The value is set back to the old value
![Screenshot from 2019-09-20 10-19-41](https://user-images.githubusercontent.com/39431745/65307417-66eb9700-db90-11e9-852a-b240fd2a188d.png)

And the thing is that the actual value in ElasticSearch is changing.
This is very confusing behaviour, could you please help us?

**Comment by lakhansamani** [comment]
@liubhub thank you for reporting this, will look into it 👍

**Comment by lakhansamani** [comment]
@liubhub sorry for the delay issue is fixed here https://github.com/appbaseio/dejavu/pull/352
