### ISSUE TITLE
Feature Request: Change Column Field Type

### ISSUE THREAD

**Issue by torrycrass** [appbaseio/dejaVu#339]
Feature Request:

Allow editing of field _type_ via dajavu.

For example. say that the field type ended up imported incorrectly for a date and time and instead of it showing up as date it instead was imported as string.

Can dejavu be updated to allow the modification of the field type from _string_ to _date_?

**Comment by lakhansamani** [comment]
@torrycrass this feature is available with Paid apps on Appbase. It is called `App Settings`
