### ISSUE TITLE
Dejavu adds <mark> tag to data, when switching from viewing to editing mode

### ISSUE THREAD

**Issue by liubhub** [appbaseio/dejaVu#341]
If a field (string field, I'm not sure about others) is selected (as text in the browser) by mouse, it is highlighted by a yellow color (and it is OK!) but if switching to the editing mode, string field contains `<mark>` tag, and it changes the data! 
After using Dejavu in our Elasticsearch index we have `<mark>data</mark>` instead of `data`

**Comment by lakhansamani** [comment]
@liubhub thanks for reporting, will look into it
