### ISSUE TITLE
Dejavu Elasticsearch Delete or Modify

### ISSUE THREAD

**Issue by umarfarooq4** [appbaseio/dejaVu#343]
Before installing it, I would like to know if there is any delete or modify feature of the data available with Dejavu. I see that it lets you add new data and add mapping but can you delete and modify the data.

**Comment by lakhansamani** [comment]
@umarfarooq4 yes you can update/delete data as well. Also there are features to bulk update/delete data.

![example](https://i.imgur.com/GWu8YiP.png)
