### ISSUE TITLE
File /dejavu/dist/app/cgi-sys/defaultwebpage.cgi not found!

### ISSUE THREAD

**Issue by arbazkiraak** [appbaseio/dejaVu#347]
After connecting to `Elastic cluster` when I click on `Search Preview` option, Page will be redirected to `File /dejavu/dist/app/cgi-sys/defaultwebpage.cgi not found!`

![image](https://user-images.githubusercontent.com/13177578/66696387-3e674080-ece9-11e9-8bbd-884adfd2e45b.png)

> Issue is on `docker latest` , `Chrome Extension`.

But using https://dejavu.appbase.io UI online works fine without any errors.

**Comment by lakhansamani** [comment]
@arbazkiraak have you added submodules required by dejavu. For more information, you can check local build [guide](https://github.com/appbaseio/dejavu/blob/dev/CONTRIBUTING.md)
