### ISSUE TITLE
HTML data not escaped

### ISSUE THREAD

**Issue by vincent-163** [appbaseio/dejaVu#349]
When viewing data that contains HTML in Data Browser, the javascript code got executed.

I expected to view HTML in raw text.

**Comment by lakhansamani** [comment]
@vincent-163 we are parsing HTML so that we can provide a better search experience with highlights example 
![](https://i.imgur.com/pmE0opE.png)

In case you need to view the raw HTML you can view it from JSON data, by clicking on `{..}` before the `_id` field
![](https://i.imgur.com/x53Xl2I.png)
