### ISSUE TITLE
Specify mount path

### ISSUE THREAD

**Issue by oroup** [appbaseio/dejaVu#356]
It would be great to be able to mount Dejavu at a particular mount path so we don't need a unique host for it. I'd love Dejavu to be able to live at /admin/dejavu because I already have an authenticating proxy in place for that URL space. Obviously this could be done with nginx or some other kind of proxy but would be great if that were unnecessary.

**Comment by lakhansamani** [comment]
@oroup since this is not a generic scenario, it would be difficult to decide mount path for all the use cases.

**Comment by benlavalley** [comment]
@oroup did you ever sort out using a proxy in front of Dejavu?

I'm finding it a bit difficult as Dejavu is responding with asset URLs that aren't including my proxy mount path, and I can't quite figure out how to resolve it. The closest I've come is using nginx's sub module which can modify HTTP responses, which allows some of the initial JS to load (vendor, main), but further requests aren't working and I feel trying to modify HTML responses is a poor approach anyway.
