### ISSUE TITLE
Search Preview in Locally built Dejavu doesn't work

### ISSUE THREAD

**Issue by aaronychu** [appbaseio/dejaVu#357]
I tried to build a Searching UI with Dejavu, so I tried to Search Preview function. It doesn't work in my local built Dejavu, however it does work when I output the Index to a JSON file and upload to appbased.io. 
by the way, my index was created with FSCrawler

**Comment by lakhansamani** [comment]
@zydisney did you followed the second step mentioned [here](https://github.com/appbaseio/dejavu/blob/dev/CONTRIBUTING.md) correctly, i.e. Adding batteries submodule?

Also, it will be helpful if you can share some errors from the browser console.

Another thing to keep in mind using Search Preview is that it only works if you have connected to a single index. If you try connecting using regex / comma-separated list of indexes then this option would be disabled.

**Comment by lakhansamani** [comment]
@zydisney closing this issue for now. Let us know if you are still facing this issue.
