### ISSUE TITLE
Type visibility

### ISSUE THREAD

**Issue by farhan687** [appbaseio/dejaVu#36]
Type should be visible only if data exists in that type.

**Comment by farhan687** [comment]
Already here: https://github.com/appbaseio/dejaVu/issues/33

**Comment by jama707** [comment]
Is it possible to make it configurable from UI?

**Comment by siddharthlatest** [comment]
@jama707 why would one want to see types that have no data in the view?

They automatically show up once data is inserted.

**Comment by jama707** [comment]
@siddharthlatest,  I'd say for adding some dummy data just for testing.

Right now, I only see 10 document types but I have more than that and they all have data. But it's not showing all of them. What could be an issue here?

Thanks!

**Comment by farhan687** [comment]
Hey @jama707 , Are you using chrome-ext., es-plugin or live gh-pages?

**Comment by jama707** [comment]
@farhan687, I'm using es-plugin. Installed using this command: `bin/plugin install appbaseio/dejaVu` It's working perfectly fine with 10 documents.

**Comment by siddharthlatest** [comment]
@jama707 I did try to replicate this behavior both on the ES plugin and chrome app with no luck.

Can you share the link to the problematic index from the chrome app? It's the share button the top left, which will share your exact data view with us.
