### ISSUE TITLE
Cannot delete row data

### ISSUE THREAD

**Issue by jzdayz** [appbaseio/dejaVu#362]
**Describe the bug**
Cannot delete row data

**Dejavu Version**
3.4.0

**To Reproduce**
1.connect es 
2.delete row data
**Expected behavior**
Expecte :  delete success
virtually : delete doesn't work

**Screenshots**
![image](https://user-images.githubusercontent.com/35563513/70962669-e8d05b00-20c0-11ea-9740-18399ae175d8.png)
![image](https://user-images.githubusercontent.com/35563513/70962677-ee2da580-20c0-11ea-8b9d-be814c96987f.png)

**Desktop (please complete the following information):**
 - OS: mac os x 10.14.6 
 - Browser chrome  78.0.3904.108

**Comment by lakhansamani** [comment]
@jzdayz thank you for reporting this.

I tried replicating this issue, but for me, deletion worked correctly. 
Can you share more information about the application and error here?

The following information will be helpful in debugging.

1. How you are connecting with Dejavu
- [ ] Web Version
- [ ] Docker Version
- [ ] Chrome Extension

2. Which ElasticSearch version cluster/index you are connecting with
3. If you can share any errors that you are seeing in the browser console
4. If you can share network error from the network tabs in browser developer tools.

**Comment by jzdayz** [comment]
> @jzdayz thank you for reporting this.
> 
> I tried replicating this issue, but for me, deletion worked correctly.
> Can you share more information about the application and error here?
> 
> The following information will be helpful in debugging.
> 
> 1. How you are connecting with Dejavu
> 
> * [ ]  Web Version
> * [ ]  Docker Version
> * [ ]  Chrome Extension
> 
> 1. Which ElasticSearch version cluster/index you are connecting with
> 2. If you can share any errors that you are seeing in the browser console
> 3. If you can share network error from the network tabs in browser developer tools.

Sorry i didn't reload , it worked , Thanks 🤝
