### ISSUE TITLE
Manage Mapping

### ISSUE THREAD

**Issue by hassaanseeker** [appbaseio/dejaVu#364]
Unable to change usecase of DataTypes.

Getting the following error.

To prevent data loss, we have restored your original mappings. You can fix this and retry.

**Comment by lakhansamani** [comment]
@hassaanseeker it would be great if you can share reproducible steps here.

**Comment by hassaanseeker** [comment]
@lakhansamani if i go to App-Settings and try to change the mapping I get the following error as below:

[https://user-images.githubusercontent.com/7199288/71147278-bdc14500-2241-11ea-9f15-403ec849a359.jpeg]

**Comment by lakhansamani** [comment]
@hassaanseeker thank you for reporting this.

This issue is not related to dejvau, so closing it here.
but we will definitely look into this and get back to you via email.

**Comment by siddharthlatest** [comment]
@hassaanseeker Just to keep you updated, this was an issue related to the appbase.io service and it's resolved now.
