### ISSUE TITLE
Deletion of rows not work due to deprecated API

### ISSUE THREAD

**Issue by ttimasdf** [appbaseio/dejaVu#377]
**Describe the bug**
Rows deletion not work in Dejavu. After clicking Delete button, Dejavu invoke the following request.
```json
POST /<indexname>/_doc/_delete_by_query?wait_for_completion=true&scroll_size=5000
{"query":{"ids":{"values":["2wpfOHABe1crLPCuLH_-"]}}}
````
Response. As shown, `deleted` shows 0 rows are deleted actually.
```json
{"took":5,"timed_out":false,"total":0,"deleted":0,"batches":0,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[]}
```

Copy the request over to Kibana and delete `/_doc` fragment inside the URL and it works.
![图片](https://user-images.githubusercontent.com/2762704/74314861-33b0db00-4db1-11ea-9d57-8ff5884e5b27.png)

Kibana also warns that `Specifying types in search requests is deprecated.`

**Dejavu Version**
Dejavu 3.4.0, docker version
Elasticsearch 7.3.0

**To Reproduce**
1. Connect to ES server in Dejavu
2. Select a row (or more) data
3. Click Delete
4. Click Reload, and row is still here.

**Expected behavior**
The document should be deleted normally.

**Screenshots**
![图片](https://user-images.githubusercontent.com/2762704/74315794-2694eb80-4db3-11ea-9546-747c79212ecc.png)
![图片](https://user-images.githubusercontent.com/2762704/74315807-2f85bd00-4db3-11ea-8dc0-cef9fb0f0b32.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 73.0
 - ES Version:

```json
{
  "name" : "elasticsearch-master-2",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "<redacted>",
  "version" : {
    "number" : "7.3.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "de777fa",
    "build_date" : "2019-07-24T18:30:11.767338Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Additional context**

**Comment by lakhansamani** [comment]
@ttimasdf thank you for reporting this!

we have fixed it here https://github.com/appbaseio/dejavu/pull/378
