### ISSUE TITLE
source editing in local development mode

### ISSUE THREAD

**Issue by littlehome-eugene** [appbaseio/dejaVu#381]
**Describe the bug**

In local development mode, modification is not applied 

**Dejavu Version**
Your version of Dejavu and how you're running it: Web, Chrome Extension or as a Docker Image.
Web, current master version. (git clone)

**To Reproduce**
follow https://github.com/appbaseio/dejavu/blob/dev/CONTRIBUTING.md

I managed to connect to the local running server.

However the code change I made to (`dejavu/packages/browser/src/reducers/mappings.js` isn't applied )

I tried running `yarn dev:dejavu` and `yarn dev:browser` (on separate terminal) after modifying the file. 

The change I made is not visible..

I can see my modification in `dejavu/node_modules/@appbaseio/dejavu-browser/lib/reducers/mappings.js`

I guess the webpack is serving `dejavu-main/node_modules/@appbaseio/dejavu-browser/lib/reducers/mappings.js`

**Expected behavior**
Modified code is visible when looking at source tab of chrome developer tool

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome

**Additional context**

**Comment by lakhansamani** [comment]
@littlehome-eugene thank you for reporting this.

I have tried fixing it, can you try with the latest `dev` branch.

**Comment by littlehome-eugene** [comment]
Thanks.. but.. It is not working

I restarted

```
yarn dev:dejavu
yarn dev:browser
```

My latest upstream commit is `78ab7eb8`

**Comment by littlehome-eugene** [comment]
the path where file is loaded changed, but it is not reflecting change I made

**Comment by littlehome-eugene** [comment]
Oh actaully, after i do `yarn install` it works fine!

**Comment by littlehome-eugene** [comment]
arr.. actually, 

files under `dejavu-main` works
but you can only see `lib` versions for files under `browser`
