### ISSUE TITLE
How a novice should start a project

### ISSUE THREAD

**Issue by lmcgit1** [appbaseio/dejaVu#383]
How should I start the project with vscode? There is no file in my batteries folder. I executed the build command and didn't write the file into it. I'm a rookie,

**Comment by lakhansamani** [comment]
@lmcgit1 you can follow instructions mentioned here
https://github.com/appbaseio/dejavu/blob/dev/CONTRIBUTING.md#starting-dev-server

**Comment by lmcgit1** [comment]
yarn run v1.22.4
$ lerna run watch --scope dejavu-main --stream
lerna info version 2.11.0
lerna info scope dejavu-main
dejavu-main: $ NODE_ENV=development webpack-dev-server --open --mode development --content-base dist/app --history-api-fallback --hot --colors --port 1358
dejavu-main: 'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
dejavu-main: ���������ļ���
dejavu-main: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dejavu-main: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run watch
lerna ERR! 'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
lerna ERR! ���������ļ���
lerna ERR! error Command failed with exit code 1.
lerna ERR!
lerna ERR! $ NODE_ENV=development webpack-dev-server --open --mode development --content-base dist/app --history-api-fallback --hot --colors --port 1358
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at D:\dejavu\node_modules\lerna\node_modules\execa\index.js:236:11
Error: Command failed: yarn run watch
'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
error Command failed with exit code 1.

$ NODE_ENV=development webpack-dev-server --open --mode development --content-base dist/app --history-api-fallback --hot --colors --port 1358
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at D:\dejavu\node_modules\lerna\node_modules\execa\index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 1,
  killed: false,
  stdout: '$ NODE_ENV=development webpack-dev-server --open --mode development --content-base dist/app --history-api-fallback --hot --colors --port 1358\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: "'NODE_ENV' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n" +
    '���������ļ���\r\n' +
    'error Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run watch',
  timedOut: false,
  exitCode: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\dejavu>

**Comment by lmcgit1** [comment]
Execute according to the command in your document, node reports an error

**Comment by lakhansamani** [comment]
Which node and yarn version are you using?

**Comment by lmcgit1** [comment]
PS D:\dejavu> node -v
v12.16.0
PS D:\dejavu> yarn -v
1.22.4
PS D:\dejavu>

**Comment by lakhansamani** [comment]
Not sure seems like windows specific error.

**Comment by lakhansamani** [comment]
Seems like there is open issue for this, you can try following solutions there.
https://github.com/lerna/lerna/issues/1457

**Comment by lmcgit1** [comment]
ok  thank you！！！！
