### ISSUE TITLE
The Chrome Extension link is broken and I cannot find it through a search

### ISSUE THREAD

**Issue by matthewsheeran** [appbaseio/dejaVu#387]
**Describe the bug**
The Chrome Extension link is broken and I cannot find it through a search - what gives!?

**Dejavu Version**
Chrome Extension

**To Reproduce**
https://chrome.google.com/webstore/detail/dejavu/jopjeaiilkcibeohjdmejhoifenbnmlh
=>
404 Not Found and cannot find a dejvu Extension through a search of the store !

WTF!?

**Comment by matthewsheeran** [comment]
Love to get this working so I can try out CSV PSV importing into ES through the Chrome Extension without installing the whole application.

**Comment by le-doude** [comment]
👍 to this

**Comment by thaenor** [comment]
https://github.com/appbaseio/dejavu/pull/386

**Comment by davkap92** [comment]
https://chrome.google.com/webstore/detail/dejavu/lcanobbdndljimodckphgdmllahfcadd?hl=e is the new one seems to work

**Comment by j0k3r** [comment]
@thaenor @davkap92 looks like it's an old version: _November 10, 2016_ 
When you open it it display a new version 0.9.0 .. with a link to that 404.

Could you help us @lakhansamani @ShahAnuj2610 ?

**Comment by tohardik** [comment]
+1, would like to have the latest version as Chrome extension

**Comment by j0k3r** [comment]
Just figured out how to build the extension on your own.

1. `git clone https://github.com/appbaseio/dejavu.git` (the repo is pretty heavy 91 Mo)
1. `cd dejavu`
1. `yarn install` (if you don't have yarn: https://classic.yarnpkg.com/en/docs/install)
1. `git submodule init && git submodule update`
1. `yarn build:chrome-extension`
1. The generated extension is located in `packages/dejavu-main/dist/app`
1. Open `chrome://extensions/` on Chrome or `brave://extensions/` on Brave
1. Enable the developer mode
1. Hit the far top left button with something like _Load the unpackaged extension_
1. Choose the previous path I talked about `dejavu/packages/dejavu-main/dist/app`
1. Profit

**Comment by siddharthlatest** [comment]
The chrome extension has been removed, and the README now doesn't mention it :-)
