### ISSUE TITLE
Deja Vu does not work without port o the url

### ISSUE THREAD

**Issue by Nekmo** [appbaseio/dejaVu#39]
Google Chrome Web console:
```
/_plugin/dejaVu/src/js/helper/feed.js
---------------------------------------------
		filterUrl: function(url) {
			if (url) {
				var obj = {
					USERNAME: 'test',
					PASSWORD: 'test',
					URL: url
				};
				var urlsplit = url.split(':');
				--> var pwsplit = urlsplit[2].split('@');
```

Exception:
```
Uncaught TypeError: Cannot read property 'split' of undefined
```

**Comment by siddharthlatest** [comment]
@Nekmo Where are you seeing this: Chrome App / Elasticsearch Plugin / Locally? If locally, which branch are you building?

**Comment by Nekmo** [comment]
Chrome console. This is a JS error on `/_plugin/dejaVu/src/js/helper/feed.js`.  The page is blank.

**Comment by siddharthlatest** [comment]
@Nekmo Are you using this as an Elasticsearch Site Plugin then?

**Comment by Nekmo** [comment]
Yes. But I use nginx with proxy_pass.

**Comment by siddharthlatest** [comment]
@Nekmo This is helpful. Which version of Elasticsearch do you use, and do you have a username:password Basic Auth set up or is it just naked ES URL?

**Comment by Nekmo** [comment]
@siddharthlatest not yet. My URL is "http://elasticsearch.mycompany.local".

**Comment by farhan687** [comment]
@Nekmo I just fixed that for gh-pages as well as elasticsearch plugin, You should uninstall previous one and install new dejavu.
 can you give it a try?

**Comment by Nekmo** [comment]
Now it works. Thanks :D
