### ISSUE TITLE
Failed to execute 'fetch' on 'Window': Invalid name

### ISSUE THREAD

**Issue by BardoQi** [appbaseio/dejaVu#390]
**Describe the bug**
I am using the docker version of dejavu.
At first we connection local elasticsearch directory. And I got error:
Failed to execute 'fetch' on 'Window': Invalid name
Possible Errors
Invalid connection string or index name
Please check if Elasticsearch cluster is up and running
And then I fllowing the config wizard on https://stackoverflow.com/questions/50231296/how-to-use-dejavu-for-elasticsearch-on-local-running-it-from-opensource-appbase
The config is :
<VirtualHost *:80>
    ServerAdmin webmaster@localhost.localdomain
    DocumentRoot "D:/es.cc/"
    ServerName rr.es.cc
    ServerAlias es.cc
    ErrorLog "logs/es.cc-error_log"
    CustomLog "logs/es.cc-access_log" common    

    #HTTP_TO_HTTPS_START
    <IfModule mod_rewrite.c>
        RewriteEngine on
        RewriteCond %{SERVER_PORT} !^443$
        RewriteRule (.*) https://%{SERVER_NAME}$1 [L,R=301]
    </IfModule>
    #HTTP_TO_HTTPS_END

    #DENY FILES
     <Files ~ (\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)$>
       Order allow,deny
       Deny from all
    </Files>

    #PATH
    <Directory />
        SetOutputFilter DEFLATE
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html index.htm default.php default.html default.htm
    </Directory>

</VirtualHost>

 <VirtualHost *:443>
    ServerAdmin webmasterexample.com
    DocumentRoot "D:/es.cc/"
    ServerName SSL.es.cc
    ServerAlias es.cc 
    errorDocument 404 /404.html
    ErrorLog "logs/es.cc-error_log"
    CustomLog "logs/es.cc-access_log" combined

    #PROXY-START
    <IfModule mod_proxy.c>
        ProxyRequests Off
        SSLProxyEngine on
        ProxyPass / http://localhost:9200/
        ProxyPassReverse / http://localhost:9200/
        
    </IfModule>
    #PROXY-END
    
    #SSL
    SSLEngine On
    SSLCertificateFile "D:/Apache2425/conf/ssl/es.cert"
    SSLCertificateKeyFile "D:/Apache2425/conf/ssl/es.key"
    SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
    SSLProtocol All -SSLv2 -SSLv3
    SSLHonorCipherOrder On
    
    #DENY FILES
     <Files ~ (\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)$>
       Order allow,deny
       Deny from all
    </Files>
    
    #PATH
    <Directory "D:/es.cc/">
        SetOutputFilter DEFLATE
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html index.htm default.php default.html default.htm
    </Directory>
</VirtualHost>

And I got error:
Failed to execute 'fetch' on 'Window': Invalid name
Possible Errors
Invalid connection string or index name

And none error in console!

When I visit my elasticearch via url https://es.cc, it could sucess, and return:
{
  "name" : "LAPTOP-DRHADAE",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "VUjq9SzSTkWJ9MnFzkJGsg",
  "version" : {
    "number" : "7.1.1",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "7a013de",
    "build_date" : "2019-05-23T14:04:00.380842Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"

  

**Dejavu Version**
Newly docker version of dejavu .

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  WINDOWS 10 
 - Browser [e.g. chrome, safari]   ：chrome
 - Version [e.g. 22]  81

**Additional context**

**Comment by BardoQi** [comment]
PS: my elasticsearch.yml is add the text:

http.port: 9200
http.cors.allow-origin: "http://localhost:1358"
http.cors.enabled: true
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.max-age: 86400
http.cors.allow-credentials: true

**Comment by BardoQi** [comment]
FIREFOX could open from URL  : http://localhost:1358/?appname=*&url=http://localhost:9200&mode=edit
and Chrome, after do sth according this url:
https://stackoverflow.com/questions/35432749/disable-web-security-in-chrome-48
also could open from URL  : http://localhost:1358/?appname=*&url=http://localhost:9200&mode=edit

but we always unable to connection with button click.

**Comment by zhangyiteng** [comment]
请问，该工具完美支持es7.10吗，我使用时导出是失败的
