### ISSUE TITLE
how can i delete some fields with dejavu

### ISSUE THREAD

**Issue by silvermoonhy** [appbaseio/dejaVu#392]
like this tittle, i want to delete some fileds with dejavu，but i can not find that。-_-;

**Comment by lakhansamani** [comment]
@silvermoonhy you cannot delete a field using Dejavu.

Schema setting is an exclusive feature of https://appbase.io/#hosting, 
You can bring your own ElasticSearch Cluster to Appbase.io or create one using Appbase hosting services.
Here is an example of that
![](https://www.dropbox.com/s/56oo571r4qmlug3/Screenshot%202020-06-26%2020.41.53.png?raw=1)
