### ISSUE TITLE
Error when running locally

### ISSUE THREAD

**Issue by DanBrk** [appbaseio/dejaVu#393]
Hi,
I am trying to run locally on Windows 10.
I followed the instructions and got the following in the log

> 0 silly input [ 'watch' ]
1 silly flags {
1 silly flags   _: [ 'run' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   stream: true,
1 silly flags   scope: 'dejavu-main',
1 silly flags   script: 'watch',
1 silly flags   args: []
1 silly flags }
2 verbose rootPath D:\dejavu-elastic
3 info version 2.11.0
4 silly existsSync D:\dejavu-elastic\VERSION
5 info scope dejavu-main
6 silly initialize attempt
7 silly initialize success
8 silly execute attempt
9 silly runScriptInPackageStreaming [ 'watch', [], 'dejavu-main' ]
10 silly getExecOpts { cwd: 'D:\\dejavu-elastic\\packages\\dejavu-main' }
11 error execute callback with error
12 error Error: Command failed: yarn run watch
12 error 'NODE_ENV' is not recognized as an internal or external command,
12 error operable program or batch file.
12 error error Command failed with exit code 1.
12 error
12 error $ NODE_ENV=development webpack-dev-server --open --mode development --content-base dist/app --history-api-fallback --hot --colors --port 1358
12 error info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12 error
12 error     at D:\dejavu-elastic\node_modules\lerna\node_modules\execa\index.js:236:11

Please advise what can it be. 

Thanks

**Comment by lakhansamani** [comment]
@DanBrk thanks for reporting,

fixed here: https://github.com/appbaseio/dejavu/commit/6ac077646796c9b238596ac41ce15f10c68c5e26
