### ISSUE TITLE
Document fields not mapping to columns

### ISSUE THREAD

**Issue by peelnpunch** [appbaseio/dejaVu#394]
**Describe the bug**
I am able to successfully connect to the index and perform CRUD operations on the raw json itself, but the document fields do not populate to columns. I only get 3 columns; _id, _index, and _type instead of the field names within the document itself.

**Dejavu Version**
Running version 3.4.2 as a Docker Image.

**To Reproduce**
1. Connect to index
2. See that only 3 columns are available.

**Expected behavior**
I expect to connect to the index and have the document fields populate to columns.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 83.0.4103.116

**Comment by lakhansamani** [comment]
@peelnpunch can you share which version of ElasticSerch you are using here?

**Comment by peelnpunch** [comment]
@lakhansamani I'm running on 7.7

**Comment by lakhansamani** [comment]
@peelnpunch we have released a new version 3.4.7.
Can you please try using that version and let us know if the issue still persists.

Also, it would be great if you can share a reproducible scenario.

**Comment by peelnpunch** [comment]
@lakhansamani that seems to have worked, thanks!
