### ISSUE TITLE
Feature request: Export as elasticsearch query

### ISSUE THREAD

**Issue by slowmove** [appbaseio/dejaVu#4]
It would be a nice feature to get implemented to be able to filter, sort etc and then export that as a elasticsearch query.

**Comment by siddharthlatest** [comment]
@slowmove We are working to support issue #1, where a user can export data (as JSON) directly from the applied filters.

What's the use-case for showing the query in JSON format?

**Comment by slowmove** [comment]
@siddharthlatest a use case for exporting the query itself would be if you want to implement it in your code for use in a script or web application of some sort.

**Comment by siddharthlatest** [comment]
@slowmove it makes sense but dejaVu's filters don't cover the breadth / depth of Elasticsearch's query DSL. That would be a better fit for something like https://github.com/appbaseio/es-querycomposer, it's not prototype ready (yet), but the premise is to have a GUI that can compose ES queries.
