### ISSUE TITLE
ç

### ISSUE THREAD

**Issue by marcgise** [appbaseio/dejaVu#406]
**Describe the bug**

**Dejavu Version**
Your version of Dejavu and how you're running it: Web, Chrome Extension or as a Docker Image.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by lakhansamani** [comment]
@marcgise I don't see a description of the issue you are facing here.

Can you update the description?

**Comment by marcgise** [comment]
Please close this Issue, was created by mistake
