### ISSUE TITLE
Can't build on local for deploy on a server

### ISSUE THREAD

**Issue by marcgise** [appbaseio/dejaVu#407]
**Describe the bug**
Mi intention is to deploy Dejavu in a server. This server is only accessible from a VPN, so I can't share the connection.

I'm trying to execute `yarn build:dejavu` hoping to have a dist folder to deploy into an Apache HTTPD Server. Maybe I'm wrong about how to deploy it, I'm not sure. But could you tell me if it's possible to do? Or should I deploy it with docker?

**Dejavu Version**
3.4.3

**To Reproduce**
`yarn build:dejavu`

**Expected behavior**
I expect to have a dist folder to deploy into an Apache HTTPD Server.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by marcgise** [comment]
I face that when dejavu starts, it's listening to 127.0.0.1:1358 address. Maybe a solution is to change it in order to listen to 0.0.0.0:1358
Can I change it from any config file?

**Comment by marcgise** [comment]
Well, I changed from package.json of dejavu-main subproject to indicate in the scripts that starts the application with the property `--host 0.0.0.0`
This way I can access from my browser, but I'm getting an error:
![image](https://user-images.githubusercontent.com/4680243/107653384-da101480-6c81-11eb-9823-a3255684bb60.png)

Any idea?

I started the application with `yarn start` in the root folder.

**Comment by lakhansamani** [comment]
@marcgise here are the steps to get production ready build
* `yarn build:dejavu:app` from the root folder
*  copy `cd packages/dejavu-main/dist/app/` folder to your apache server hosting dir

**Comment by marcgise** [comment]
Well, I finally get it... Adding a property in the webpack.config.js file:
```
devServer: {
compress: true,
public: "myserver.es"
}
```

**Comment by lakhansamani** [comment]
@marcgise that will just start it in dev mode.
To run in production make sure you create build and follow the above steps.
