### ISSUE TITLE
dejavu as a kibana plugin

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejavu#41]
With Elasticsearch 5.0 being GA, the site plugins have been removed. Instead, Elastic encourages Kibana plugins.

While dejavu can be still usable with the github hosted app and chrome app (which is going away next year), we should consider supporting dejavu as a Kibana plugin.

**Comment by xycloud** [comment]
any progress about this?

**Comment by siddharthlatest** [comment]
@xycloud Have had some people ask about it. We don't have this on an immediate roadmap, however if someone contributes, we would be more than happy to add it in.

**Comment by siddharthlatest** [comment]
We recommend using the docker image https://hub.docker.com/r/appbaseio/dejavu/ if you are on ES 5.0 and above.

**Comment by siddharthlatest** [comment]
Will not be pursuing this in the near future as we already have a docker image, but we would accept a PR on this if someone gets around to it.
