### ISSUE TITLE
chrome extension cannot be found

### ISSUE THREAD

**Issue by mmcer** [appbaseio/dejaVu#417]
**Describe the bug**
By following the readme.md, I want to install the chrome extension, but google report 404 error, please hep to check the url "https://chrome.google.com/webstore/detail/dejavu/jopjeaiilkcibeohjdmejhoifenbnmlh"

**Comment by CherryDT** [comment]
Issue still exisitng...

**Comment by siddharthlatest** [comment]
Have removed the reference to it from README.
