### ISSUE TITLE
Select and copy a record content

### ISSUE THREAD

**Issue by KarmeleJisc** [appbaseio/dejavu#43]
Using ElasticSearch plugin via Chrome app I cannot select the content of a record. When I click on the brackets icon {...}  I can see the content but I cannot select and copy it

**Comment by siddharthlatest** [comment]
I can confirm the issue.

**Comment by farhan687** [comment]
Fixed over here: 28299cda32a17eba8270bbf7da177fb1eb5cff7e

**Comment by siddharthlatest** [comment]
Released in `v0.8.3`, available in the chrome store.
