### ISSUE TITLE
 dejavu 3.5.3 have a XSS vulnerability

### ISSUE THREAD

**Issue by burpheart** [appbaseio/dejaVu#430]
**Describe the bug**
I am trying to use dejavu, but when I try to use the search preview I find that the html tags in my search results are rendered by the browser and the js scripts in them are executed

**Dejavu Version**

Web 3.5.3

**To Reproduce**
1. Importing data containing html tags to es
2. Go to Search Preview
2. Search result values are rendered as html

**Expected behavior**
Data is rendered as text

**Screenshots**
![img](https://user-images.githubusercontent.com/35721255/155866240-163cd3de-3575-4a3b-af06-68bef1de5fbd.png)
**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox 
 - Version 97.0.1

**Additional context**

**Comment by siddharthlatest** [comment]
@burpheart The ability to render HTML is important (to support highlighting use-case for example). That said, we've opted for using the [dompurify](https://www.npmjs.com/package/dompurify) package here to prevent XSS attacks. This is released as part of Dejavu v3.6.0.

**Comment by burpheart** [comment]
Can this vulnerability be assigned a CVE number?

> @burpheart The ability to render HTML is important (to support highlighting use-case for example). That said, we've opted for using the [dompurify](https://www.npmjs.com/package/dompurify) package here to prevent XSS attacks. This is released as part of Dejavu v3.6.0.
