### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by AsedMorteza** [appbaseio/dejaVu#444]
Hello
To be very brief !
I can't connect !
This is my Docker Compos configuration
When I enter the elastic address(http://0.0.0.0:9200), it does not connect...
In addition, I see my indexes easily in Kibana

  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    logging:
      driver: none
    container_name: c-es
    environment:
      - discovery.type=single-node
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=http://dejavu:1358,http://dejavu:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - "9200:9200"
    networks:
      - test
    ulimits:
      memlock:
          soft: -1
          hard: -1
    restart: unless-stopped

  dejavu:
    image: appbaseio/dejavu:3.6.0
    container_name: dejavu
    ports:
        - '1358:1358'
    links:
        - es7
    networks:
        - test

**Comment by siddharthlatest** [comment]
@AsedMorteza Your docker compose looks correct. Can you share the output of `docker-compose ps`? And you should then be connecting to Dejavu, for example: if this is being run on localhost, it should be http://localhost:1358

**Comment by AsedMorteza** [comment]
c-es                      /tini -- /usr/local/bin/do ...   Up             0.0.0.0:9200->9200/tcp,:::9200->9200/tcp, 9300/tcp                                                                                      
dejavu                    docker-entrypoint.sh /bin/ ...   Up             0.0.0.0:1358->1358/tcp,:::1358->1358/tcp 

dejavu is up at http://0.0.0.0:1358 but unable to connect els

**Comment by siddharthlatest** [comment]
@AsedMorteza Thanks for the above! Can you share the exact error you see in the browser when you connect to it?

**Comment by AsedMorteza** [comment]
![Screenshot from 2022-07-13 11-47-27](https://user-images.githubusercontent.com/107461328/178674392-9fd10d35-2058-4c48-ab78-58f38f5cccd9.png)


"""Unable to connect

Possible Errors
Invalid connection string or index name
Please check if Elasticsearch cluster is up and running"""

**Comment by siddharthlatest** [comment]
@AsedMorteza What does doing a `curl http://0.0.0.0:9200` return?

**Comment by AsedMorteza** [comment]
{
  "name" : "3b39b51e76d5",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "f0zUOG7qQYinfn3mckzpSA",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "docker",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by siddharthlatest** [comment]
@AsedMorteza Thanks! This seems okay too. One more recommendation I can think is to type in a concrete index name instead of `*`.

When you're connecting to Dejavu from the browser, one of the endpoints to ES is failing. Can you keep your network tab open and share the details of the failing request. You will see an option to copy the request as cURL or you can paste the screenshot here of the failing request (see ref below).

![](https://i.imgur.com/7mSIne8.png)

**Comment by siddharthlatest** [comment]
@AsedMorteza I spotted the issue, it should be failing to connect with a CORS error.

> - http.cors.allow-origin=http://dejavu:1358,http://dejavu:1358

Change this row in your docker-compose to below:

> - http.cors.allow-origin=http://0.0.0.0:1358

The `http.cors.allow-origin`'s value should point the host to the browser origin from where you're going to access ES from.

**Comment by AsedMorteza** [comment]
Thank you very much for the quick handling and help
