### ISSUE TITLE
BUG - Can't update a document, _type is empty/undefined

### ISSUE THREAD

**Issue by valentin-dlack** [appbaseio/dejaVu#448]
**Describe the bug**
When I try to update a value of a document in DejaVu it doesn't work. The `_type` seems to be empty or undefined and when I check the PUT request in the chrome network inspector, I get a 400 Bad Request and the path is `http://localhost/products/**undefined**/SEF_E4QBVQOW--Rmb43L?refresh=wait_for` (see screenshots). I don't know why it does this.

**Dejavu Version**
I run Dejavu 3.6.0 as a Docker Image (with elasticsearch 8.4.3)

**To Reproduce**
1. Connect to the cluster
2. Go in the Data Browser in Edition Mode
3. Try to update any value of a document 

**Expected behavior**
The document must be updated

**Screenshots**
![image](https://user-images.githubusercontent.com/64978672/197986580-e663dfad-ffbf-4f35-be8e-3cd652d34ba8.png)
![image](https://user-images.githubusercontent.com/64978672/197986728-c51c9fab-9835-4c2b-9dbc-c985c2b8c972.png)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro 5.15.74
 - Browser: Chrome
 - Version: 107.0.5304.68

**Additional context**
I run elasticsearch on docker also, and fill it with a little nodeJs app. Also, the _type appears when I use ElasticVue for exemple.

**Comment by dmoskovtsov** [comment]
I see same behaviour when connected to the v8.4.3 instance of ElasticSearch from https://dejavu.appbase.io/

**Comment by siddharthlatest** [comment]
@dmoskovtsov @valentin-dlack can confirm this behavior.
