### ISSUE TITLE
Single Tool for ElasticSearch

### ISSUE THREAD

**Issue by fizerkhan** [appbaseio/dejavu#46]
Thanks for the great product. I love all the three products such as GEM, Mirage and Dejavu.

I am heavily using them for my local testing. I am facing the problem that I have to frequently switch between tabs. It is really disturbing. Atleast Mirage and Dejavu can be single app so developer can visualise and then test different query from same page.

**Comment by siddharthlatest** [comment]
@fizerkhan thanks for the love!

We are considering how to integrate them better. I will leave this issue open till we file another one that's more specific on how we will accomplish that.

**Comment by fizerkhan** [comment]
@siddharthlatest Great. I will wait 👍

**Comment by siddharthlatest** [comment]
@fizerkhan the new release `v0.10.0` bakes in querying functionality and simultaneously mirage `v0.6.x` adds a new data view for the results based on dejavu.

Closing this issue.

**Comment by fizerkhan** [comment]
@siddharthlatest Thanks. Great news. I will take a look at it.
