### ISSUE TITLE
Exporting CSV/JSON Returns Undefined

### ISSUE THREAD

**Issue by Jeandsmith** [appbaseio/dejaVu#478]
**Describe the bug**

Clicking on the export button and selecting CSV or JSON returns `undefined`

**Dejavu Version**
3.6

**To Reproduce**
1. Go to `Data Browser`
2. Click on `Export`
3. Click on `Export X documents` check box
4. Click on `Download as (CSV/JSON)`

**Expected behavior**
Expected behaviour is for the documents to download in the selected format.

**Screenshots**
<img width="647" alt="image" src="https://github.com/appbaseio/dejavu/assets/11911593/75bc5753-c78d-4539-a51c-ed727478a3f0">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6
 - Browser Chrome
 - Version Chrome 118

**Comment by siddharthlatest** [comment]
@Jeandsmith Which version of Elasticsearch / OpenSearch are you on?

**Comment by siddharthlatest** [comment]
I noticed a scenario for ES v8.x when indexes where originally created in ES v7.x. This should be addressed with 3.8.3.

However, given version specific support, it may need a revisit with a major ES / OS version update.
