### ISSUE TITLE
Chrome extension installation steps

### ISSUE THREAD

**Issue by MrOrz** [appbaseio/dejavu#48]
I tried installing the chrome extension and connects to `localhost:9200`. It kept loading.

Finally I got it working by adding the following to `config/elasticsearch.yml`:

```
 http.port: 9200
 http.cors.allow-origin: "chrome-extension://jopjeaiilkcibeohjdmejhoifenbnmlh"
 http.cors.enabled: true
 http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization"
 http.cors.allow-credentials: true
```

I think there should be error messages that is more informative, and the need for configuring `allow-origin` to `chrome-extension` should be addressed in README.

**Comment by siddharthlatest** [comment]
@MrOrz Added a note for chrome-extension users here, thank you - https://github.com/appbaseio/dejavu/commit/334bb46bccfbfab1fff76ef584e9a0c2fa6d6b07.
