### ISSUE TITLE
Provide pre-compiled application in release

### ISSUE THREAD

**Issue by cweiske** [appbaseio/dejaVu#482]
**Is your feature request related to a problem? Please describe.**
The dejavu releases only contain the source code zip files, so I can't download them and run the application in the browser.

**Describe the solution you'd like**
Each github release should have a zip file with the compiled `dist` folder in it. That way I could download it and run it without any compilation steps. (e.g. via `php -S 127.0.0.1:8080`)

**Workaround**
I had to resort to starting the docker image and copying `/dejavu/packages/dejavu-main/dist/app` to my host.

**Comment by siddharthlatest** [comment]
Thank you for bringing this up, this is added with the 3.8.3 release.
