### ISSUE TITLE
Dockerfile does not build

### ISSUE THREAD

**Issue by manalejandro** [appbaseio/dejaVu#484]
**Describe the bug**
Dockerfile does not work.

**Dejavu Version**
Latest repo.

**To Reproduce**
docker build -t dejavu .

**Desktop (please complete the following information):**
All platforms

**Additional context**

***Node version bug solved***

```$ git diff
diff --git a/Dockerfile b/Dockerfile
index daf606b0..b776519f 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -11,7 +11,9 @@ RUN apk --no-cache update \
 
 ADD . /dejavu
 
-RUN yarn \
+ENV NODE_OPTIONS=--openssl-legacy-provider
+
+RUN yarn config set ignore-engines true -g && yarn \
     && yarn cache clean && yarn build:dejavu:app \
     && rm -rf /dejavu/node_modules \
     && rm -rf /tmp/*
```

**Comment by siddharthlatest** [comment]
Thanks for reporting. A fix for this is added in the 3.8.3 release.
