### ISSUE TITLE
Can 'input_state' potentially save an actual query as well as the client, index and types contexts?

### ISSUE THREAD

**Issue by Analect** [appbaseio/dejavu#51]
Thanks for this project and its sister `mirage`.  Both serve an important gap in the ES GUI space.

I've been playing around with a local installation against my data and trying to get a better feel for how 'input_state' is working, in terms of it somehow encoding a 'state' ... ie. client-connection info, index selection and perhaps type selection.  I don't think it's base64 encoded ... but I can see you are  using cryptojs in some way.

Are there any spec documents as to how this is working ... or perhaps an example of an encoded/decoded payload.

I was also wondering if it's possible to include a query that gets applied to the given 'state', and pass that as part of the url ... in either encoded or plain JSON form?

Thanks.

**Comment by siddharthlatest** [comment]
@Analect you are right on point about queries, it's in the roadmap for the next version release (very soon). We are supporting them in plain JSON stringified format.

Also about the `input_state`, it's base64 encoded and then lzma compressed (losslessly). Will add a spec explaining the query string parameters.

**Comment by Analect** [comment]
@siddharthlatest 
Thanks for the update. Look forward to the new release and `input_state` docs. Will close this out.

**Comment by siddharthlatest** [comment]
@Analect the release is already out v0.10.0. Will add the docs shortly.

**Comment by Analect** [comment]
@siddharthlatest 
I did keep an eye out for enhancements to docs ref this, but haven't found anything.  I expect you haven't found time to add.  Any chance you might be able to give some guidance here?

I'm interested in passing `type` and `query` parameters to dejavu in order to pre-filter and capture this in the url call.

For instance, this would be a query I would run against a type `infrastructure0`.
```
{
  "query": {
    "term": {
      "bloomberg_ticker.keyword": "BHP AU"
    }
  }
}
```
This is what the url looks like with an empty query (ie. just specifying the type)

`http://myserver.com:1358/#?input_state=XQAAAAJ-AAAAAAAAAAA9iIqnY-B2BnTZGEQzY8iywCz7kVDXlo4SwicGxZ5gD8Sf_I-qvQcPy1iJQiI8X9VLF6CqVrz8xdIG-DoyZV9q5GaamGF48sReFc-_mBhUIbunVAnLxIFA3bFy3OgalOJNGXh2HOHh___nKSAA`

... and this is what it looks like including the query above.

`http://clienta.analect.com:1358/#?input_state=XQAAAAIcAQAAAAAAAAA9iIqnY-B2BnTZGEQzY8iywCz7kVDXlo4SwicGxZ5gD8Sf_I-qvQcPy1iJQiI8X9VLF6CqVrz8xdIG-DoyZV9q5GaamGF48sReFc-_mBhUIbunVAnLxIFA3bFvmLaCubxJdGAiaPTKsU5ojUgoLnigjJEK_0cC28fjyhBkdUWMTrbclHYbi24YPSFg_Vu8qZN3V_9GH_B9yAKD2EF4oBMRbRpkahGBD518t4NB60k1fpX0VpNpudlfoIsODh_-IXzHBZp4TSd2v_iZtWFNLh2xmAv-9cIGCA`

I would love to be able to see the method used to arrive at this second command ... in terms of the form applied to combining the `index`, `type` and `query` and the transformation via `base64` to arrive at the above url. As per your response further up, you are applying some compression too ... so it's hard for me to backward engineer how this is working. 

Thanks.

**Comment by farhan687** [comment]
hey @Analect 

You can pass query using query parameter as shown below.

Let's take an example of `2016primaries` appbase app.
appname: 2016primaries
credentials: https://Uy82NeW8e:c7d02cce-94cc-4b60-9b17-7e7325195851@scalr.api.appbase.io

Query with type(on which you want to apply query)
```js
{
     query: {
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "County": "Lyon"
              }
            }
          ]
        }
      }
	},
	type: ["iowa_democrats"]
}
```

Now stringify query and pass it with `query` parameter.
over here it will be /dejavu/live/#?input_state=.........&query={"query":{"query":{"bool":{"must":[{"match":{"County":"Lyon"}}]}}},"type":["iowa_democrats"]} 

Full url: https://opensource.appbase.io/dejavu/live/#?input_state=XQAAAAIUAQAAAAAAAAA9iIqnY-B2BnTZGEQz6wkFsnR3mLY6qp78UrdyiX4kf3rJXqxmkCAfGPRGyyY4NGU7xDzBus7B3hXJNG4yyaH1H8guySgP4Wo-ZoNcdRwQLUR0z6eRlUmgmT3EhyDSjc2FAfNrp-UQUzBSnnBhUAyhUc5rRuLg8nvk_kwBPzKRYm3cbZYJcsTQD9KmVE7xkzS7d0uEuecEtv0wF34Jkss8G3rrGFXbtnJ5CFRK0BZM7eHrakh4y0s6_QBPD0o1KiUFfl1GY54RawIGIt611hygqC0OhxcfQc3bIJD2IgWqQqn9-5QigA&query={"query":{"query":{"bool":{"must":[{"match":{"County":"Lyon"}}]}}},"type":["iowa_democrats"]}

You can create different queries in mirage and pass in dejavu as shown above.

**Comment by Analect** [comment]
@siddharthlatest 
Thanks.
Ideally I want to be able to pre-form the `input_state` part too ... so that I can automatically feed a query directly to dejavu.

So when I login with the `appname` and `credentials` ... it adds this `input_state` to the url.

`https://opensource.appbase.io/dejavu/live/#?input_state=XQAAAAJvAAAAAAAAAAA9iIqnY-B2BnTZGEQz6wkFsnR3mLY6qp78UrdyiX4kf3rJXqxmkCAfGPRGyyY4NGU7xDzBus7B3hXJNG4yyaH1H8guySgP4Wo-ZoNcdRwQLUR0z6eRlUmgmT3EhyDSjc2FAfNrp-TaiyEkMn__7rsAAA`

Then if I add the query, it updates/extends the `input_state` (presumably to explicitly select type `iowa_democrats`?).  The `-TaiyEkMn__7rsAAA` at the end of the url above gets replaced with `UQUzBSnnBhUAyhUc5rRuLg8nvk_kwBPzKRYm3cbZYJcsTQD9KmVE7xkzS7d0uEuecEtv0wF34Jkss8G3rrGFXbtnJ5CFRK0BZM7eHrakh4y0s6_QBPD0o1KiUFfl1GY54RawIGIt611hygqC0OhxcfQc3bIJD2IgWqQqn9-5QigA`

`https://opensource.appbase.io/dejavu/live/#?input_state=XQAAAAIUAQAAAAAAAAA9iIqnY-B2BnTZGEQz6wkFsnR3mLY6qp78UrdyiX4kf3rJXqxmkCAfGPRGyyY4NGU7xDzBus7B3hXJNG4yyaH1H8guySgP4Wo-ZoNcdRwQLUR0z6eRlUmgmT3EhyDSjc2FAfNrp-UQUzBSnnBhUAyhUc5rRuLg8nvk_kwBPzKRYm3cbZYJcsTQD9KmVE7xkzS7d0uEuecEtv0wF34Jkss8G3rrGFXbtnJ5CFRK0BZM7eHrakh4y0s6_QBPD0o1KiUFfl1GY54RawIGIt611hygqC0OhxcfQc3bIJD2IgWqQqn9-5QigA&query={"query":{"query":{"bool":{"must":[{"match":{"County":"Lyon"}}]}}},"type":["iowa_democrats"]}`

It could be that I only need to understand how the initial `input_state` `XQAAAAIUAQAAAAAAAAA9iIqnY-B2BnTZGEQz6wkFsnR3mLY6qp78UrdyiX4kf3rJXqxmkCAfGPRGyyY4NGU7xDzBus7B3hXJNG4yyaH1H8guySgP4Wo-ZoNcdRwQLUR0z6eRlUmgmT3EhyDSjc2FAfNrp-UQUzBSnnBhUAyhUc5rRuLg8nvk_kwBPzKRYm3cbZYJcsTQD9KmVE7xkzS7d0uEuecEtv0wF34Jkss8G3rrGFXbtnJ5CFRK0BZM7eHrakh4y0s6_QBPD0o1KiUFfl1GY54RawIGIt611hygqC0OhxcfQc3bIJD2IgWqQqn9-5QigA` is generated programmatically.

**Comment by Analect** [comment]
Sorry ... realise it was @farhan687 that responded above!

**Comment by siddharthlatest** [comment]
@Analect This is my understanding of how this part works:

```
{
       config: {
                url: 'https://$user:$pass@host',
	        appname: '$app'
        },
	selectedType: ['type1', type2']
}
```

A stringified version of the above object is [lzma compressed](https://github.com/LZMA-JS/LZMA-JS#how-to-use). This returns a [buffer](https://nodejs.org/api/buffer.html) which is translated to string and that string forms the value of the **input_state** query string parameter.

This is the file where it happens - https://github.com/appbaseio/dejavu/blob/dev/live/src/js/helper/urlShare.js.

**Comment by Analect** [comment]
@siddharthlatest @farhan687  Thanks.
