### ISSUE TITLE
pls add screenshot 

### ISSUE THREAD

**Issue by xycloud** [appbaseio/dejavu#52]
its fine if there is a screenshot  of dejavu in README

**Comment by siddharthlatest** [comment]
Sure, would you like to contribute? Send over a pull request  :)

**Comment by xycloud** [comment]
yes, I just make a pull request

**Comment by siddharthlatest** [comment]
@xycloud We had gifs for dejavu features that were broken, I have updated them. Thanks for pointing it out.
