### ISSUE TITLE
Does dejavu support basic auth?

### ISSUE THREAD

**Issue by bbalakri** [appbaseio/dejavu#54]
I configured basic auth using search guard. I could access DB using REST but not through dejavu.

**Comment by siddharthlatest** [comment]
@bbalakri dejavu supports Elasticsearch indexes with basic auth, can you share a screenshot and console log when you are seeing this?

**Comment by bbalakri** [comment]
Hi Siddharth,
Thanks for following it. I used the Search Guard. CORS setting seems to be causing the issue. Once that's removed, everything is OK. Now I am using dejavu as plugin with no issues.

**Comment by siddharthlatest** [comment]
@bbalakri awesome to hear, closing this issue.
