### ISSUE TITLE
Adding bulk data with "Add Data"

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejavu#56]
While we have Elasticsearch REST APIs to index data (including with bulk options), adding a feature to add JSON documents in bulk right within `dejavu` would improve accessibility.

### Implementation Idea:

Multiple documents can be supported within the "Add Data" modal using an outer Array. Since Elasticsearch docs need to be an object, supporting this should not cause conflicts with the existing "Add Data" method.

![Add Data](https://i.imgur.com/L2wi8qb.png)

We will also add a helper text explaining how to add bulk data in the modal itself.

`Note:` This geared towards accessibility (for example: users converting CSV data to JSON and importing it, or exporting data from another JSON service and importing it), and in its current form -- only supports adding bulk index requests (update, delete not supported).

**Comment by farhan687** [comment]
Fixed here: 0353e71709fe96c59b4580ba3cebd9380e552ffa
