### ISSUE TITLE
Connection Issue Reporting

### ISSUE THREAD

**Issue by markshervey** [appbaseio/dejaVu#6]
Is there a way to know what's happening with a connection?  I'm trying to connect to our instance and get no feedback on what the connection issue is.

**Comment by farhan687** [comment]
Can you show me the error in network or any error in console?

**Comment by markshervey** [comment]
I'm using the Chrome App.  When I click connect it's just unresponsive, there is no indication that anything has happened.

**Comment by markshervey** [comment]
Is there a way I can get a console up on a Chrome App?  Run the standalone app in the browser?

**Comment by farhan687** [comment]
In chrome app, I guess they don't allow console, but you can try with es plugin for now.

I will update you for chrome app.

**Comment by markshervey** [comment]
Ran the plugin and it looks like a CORS issue, so the app's working fine.  It would be nice to get an error message about it maybe... not an issue, just a feature request I guess.  Thanks for being so responsive!  Looks like a great tool.

**Comment by farhan687** [comment]
Chrome-extension CORS issue is resolved in https://github.com/appbaseio/dejaVu/commit/fdeb7a21c44f64b43cfc07ec7857596752b51aa3

**Comment by siddharthlatest** [comment]
Published in v0.3, https://chrome.google.com/webstore/detail/dejavu/lcanobbdndljimodckphgdmllahfcadd.

**Comment by markshervey** [comment]
Cool.  It worked for me!  Thanks!
