### ISSUE TITLE
does not work with amazon elastic search

### ISSUE THREAD

**Issue by fachhoch** [appbaseio/dejaVu#61]
I tried connecting to amazon elasticsearch , it did not work, I tried with 2.3 and 5.1, both failed.  It shows authentication error.  My aws elastic search has no authentication.

**Comment by siddharthlatest** [comment]
@fachhoch Is your cluster publicly accessible? Can you share with us the URL (if public) or the exact network error response that you are seeing when you try it?

**Comment by siddharthlatest** [comment]
Closing this due to lack to activity.
