### ISSUE TITLE
Only first 10 types are shown

### ISSUE THREAD

**Issue by max-sydorov** [appbaseio/dejaVu#63]
I have an index with many types (aka tables) and in Types tab only first 10 ones are shown. I guess this is default size for elasticsearch queries. Can you fix it please?
I use ES 1.4.1.

**Comment by siddharthlatest** [comment]
Types are fetched from /_mappings endpoint. The ES query's size limitation shouldn't apply.

Do you see any error(s) in the console?

**Comment by max-sydorov** [comment]
Yes, I see some errors. See attached screenshot.
<img width="1423" alt="screen shot 2017-03-28 at 15 44 10" src="https://cloud.githubusercontent.com/assets/5852281/24424117/746e99d2-13cd-11e7-825e-67b369182c2b.png">

**Comment by siddharthlatest** [comment]
@maxsidorov the errors seem unrelated, they simply note that you are using a non-realtime ES instance. Will check if there is an actual issue, could potentially just be a missing scroll UI to show more types.

If you inspect the network tab and look for /_mapping requests response, do you see all the types that exist in the app? If yes, this is a UI issue. We will investigate and push out the fix in the next coming release.

**Comment by max-sydorov** [comment]
@siddharthlatest, you are right. I see all types in the /_mapping response. Looks it's UI issue. Thanks

**Comment by farhan687** [comment]
Fixed here: 4cef3c6c6dc81f14490127e1ef4c0375058e6c99
