### ISSUE TITLE
Elaticsearch v5.3.0 coule not install dejavu

### ISSUE THREAD

**Issue by zonglu666** [appbaseio/dejaVu#66]

**Comment by siddharthlatest** [comment]
@zonglu520 Starting Elasticsearch v5.0.0, site plugins have been removed. Alternatives are:

1. Using the docker image - https://hub.docker.com/r/appbaseio/dejavu/ (ideal replacement for the site plugin),
2. Using the chrome extension - https://chrome.google.com/webstore/detail/dejavu/jopjeaiilkcibeohjdmejhoifenbnmlh,
3. Using the hosted app at https://opensource.appbase.io/dejavu.
