### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [appbaseio/dejaVu#7]
Hi there! This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because may you get some extra support for dejaVu.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like hamburgers. 
I know that the open source is free, but it's okay if someone want to contribute in other way.

Thanks for this work man!

**Comment by siddharthlatest** [comment]
We aren't accepting donations atm, good luck with beerpay - looks like a good start.
