### ISSUE TITLE
10mb file upload limit

### ISSUE THREAD

**Issue by PAK90** [appbaseio/dejaVu#78]
I have an ~80mb file (array of a few thousand objects) which I want to import, but can't due to the 10mb limit. Is there any way around this?

**Comment by siddharthlatest** [comment]
Currently, we are enforcing the 10MB limit as the import feature is very new and we don't want people to import arbitrarily large files.

A workaround is to break your file into multiple chunks, each less than 10MB (and with less than 100k records). You can then go through the import process multiple times; pick the import destination as an existing app starting the 2nd time onwards.

I should also note that this feature is `experimental` and your mileage may vary.

**Comment by siddharthlatest** [comment]
@PAK90 We have increased the upload limit to 100MB, the import feature still remains experimental ;)

**Comment by gh-doot** [comment]
'ight why did i litterally come in here from google ._.
