### ISSUE TITLE
Export to CSV or Excel

### ISSUE THREAD

**Issue by Akhilesh-Anb** [appbaseio/dejaVu#80]
Hi,

i love this plugin for ES. Can we get an option for downloading the data in excel sheet?

If yes please let me know. We have 40GB size of indices. It will be helpful if we have excel report generation

Thanks,
Akhilesh Appana

**Comment by siddharthlatest** [comment]
@Akhilesh-Anb We would love to support an export to csv but it is not currently on our roadmap. A workaround is to use online convertors for JSON -> CSV. That said, if someone would be willing to make a feature PR for this, we would welcome it!

**Comment by farhan687** [comment]
Implemented here e6f19c542516d5d9b412732a78b33d1bca9a4159
