### ISSUE TITLE
Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by brylie** [appbaseio/dejaVu#81]
When running `npm install` I noticed the following security warning:

```
Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

Disregard, if this is already a known issue.

**Comment by farhan687** [comment]
hey @brylie 
Minimatch is gulp dependency,
For more info check this issue https://github.com/gulpjs/gulp/issues/1604
