### ISSUE TITLE
Guidance how to include as static frontend

### ISSUE THREAD

**Issue by koh-osug** [appbaseio/dejaVu#84]
So far i'm using Kibana 3 which can be configured with an URL and a logstash column configuration which data to show. Kibana 4+ is using its own server which is a very unpleasant development and is not appreciated. I want to have the classical Kibana 3 approach which is completely using client side rendering. I want to be able to use dejavu as a replacement to support also elastic search 5+. How can I configure dejavu to connect to an Elastic search instance providing an URL. How can I configure what columns to show and in which order?

**Comment by siddharthlatest** [comment]
@koh-osug The [dejavu chrome extension](https://chrome.google.com/webstore/detail/dejavu/jopjeaiilkcibeohjdmejhoifenbnmlh) can work client-side. Alternatively, if you are open to the idea of running a docker container, there is also a [dejavu image on docker hub](https://hub.docker.com/r/appbaseio/dejavu/). The container can run on the same host machine as the ES cluster node(s), or a different one.

While ordering of column is not supported yet, dejavu can be configured to show particular columns.

![](https://i.imgur.com/cJI1NQF.png)

**Comment by koh-osug** [comment]
Hi, I actually targeted for dejavu to have a light weight implementation because I had the impression that dejavu wants to be an alternative for Kibana 3. Kibana 4+ were complicating things like introducing a server. It should be startable from inside the server provided HTML. The chrome extension is a burden for the user because he would have to open this, enter an URL and also the credentials. It also does not work in all browsers. A docker image is an additional server, this makes the deployment complex and is out of scope. I'm looking for a java script function like `startMe(<url>, <some other config>)` like it was possible with Kibana 3. Because dejavu starts up somehow its logic I would have assumed this initialization is somewhere hidden.

**Comment by siddharthlatest** [comment]
@koh-osug There is a hosted version of the app available at https://opensource.appbase.io/dejavu/live/, that should work on all modern browsers. It runs on github pages. I think this is what you are looking for.

If you wish to create your own set up that is similar to that, check out the build config in the `gh-pages` branch of the repo. It currently starts its own static server, but it should not be hard to change it to use an existing server.

**Comment by koh-osug** [comment]
OK, thanks a lot. I will give this a try.

**Comment by koh-osug** [comment]
Seems to be not easy. To goal was to get rid of this welcome credentials page where the data of the ES cluster. This does not make sense for my server view, the user is already authenticated. I tried to remove this BRANCH differences and the config and try to find the place where the URL to the ES cluster has to be defined, but it insists to ask for a username and password, although this is handled by a proxy. When entering there fake data it loads, but it is still searching for the config file and want to open a web socket connection. Because the scripts are minified it is not possible to remove this easily. I went back to the initial version with the unpatched feed.js

In the config.js I found:

```
	"hostname": "scalr.api.appbase.io",
	"appname": "2016primaries",
	"username": "pW2DT42Cw",
	"password": "a4fae72b-014d-4600-bb6e-544be036db40",
	"email":"farhan687@gmail.com",
	"url":"https://Uy82NeW8e:c7d02cce-94cc-4b60-9b17-7e7325195851@scalr.api.appbase.io" 
```

What are theses values? I only have an ES cluster address, I do not user username and password, this is handled by the proxy and the existing session cookie by the server where the HTML is integrated. I also do not have the other values. I only have a server address with the ES URL where the server proxy is forwarding the traffic to the ES cluster. Although I added everywhere fake value I still get to the welcome credentials page and it asks for the cluster info, although the config file is filled. What do I have to do next to get rid of the unneeded config values and the welcome credentials page? Basically I only want to see the columns of the dashboard with all the filters automatically loaded from a fixed ES cluster URL.

**Comment by siddharthlatest** [comment]
@koh-osug The credentials are for a demo app that we include in the hosted app. They shouldn't matter.

Dejavu stores the state (current app, cluster host, any other UI selections) in the URL. One quick way for you to route directly to the app page is set up a redirect on a specific page to go to this URL.

The other option to set it directly in the view would involve changing it in the file `live/src/js/helper/feed.js`'s **init()** function.

**Comment by koh-osug** [comment]
Thanks for the help. Some requirements have been added on my, e.g. to have a dashboard and some visualizations, so I think, I cannot get around to have full blown Kibana setup now.
