### ISSUE TITLE
Filter queries are being overridden on page change

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejaVu#89]
When applying a filter in the UI, the current view changes to reflect the query condition. However, on page change, the query condition is overwritten by a `match_all` query.

### Initial query:

![](https://i.imgur.com/k9b07N7.png)

### Query after page change:

![](https://i.imgur.com/eJwwaJY.png)

**Comment by farhan687** [comment]
Fixed here: 8a575c94b8616fc772d6a010ce4ff63e374edd0f
