### ISSUE TITLE
Chrome extension: clicks don't work on certain elements

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dejaVu#9]
For instance, the JSON data is not selectable. And the "watch video" and "Create your own ElasticSearch in cloud with appbase.io" hyperlinks don't open in a browser.

Both could be separate issues, nonetheless, something we should look into.

**Comment by farhan687** [comment]
Redirect to watch video & Appbase is fixed in https://github.com/appbaseio/dejaVu/commit/dbb1afdf5ee55655282c95ee9a8ba56b1ec299c5

**Comment by farhan687** [comment]
Json and type/id is now selectable : fixed in https://github.com/appbaseio/dejaVu/commit/401789f53de987d8d8cd2e6000d1cffe8fb62841

**Comment by siddharthlatest** [comment]
Works in Chrome v0.3, closing.
