### ISSUE TITLE
Connect to AWS Elastic Search

### ISSUE THREAD

**Issue by rkaplan-sx** [appbaseio/dejaVu#90]
Is it possible to connect to AWS Elastic Search using an AWS signature (access key and secrety key).  It looks like dejavu only supports basic auth.  Thanks for your help.

**Comment by siddharthlatest** [comment]
@rkaplan-sx This isn't possible currently, if someone were to submit a PR for it, we would be happy to support it.

**Comment by itstueben** [comment]
One year later.  Supports dejavu AWS Elasti Search?

**Comment by siddharthlatest** [comment]
@itstueben You can use it via a proxy (think API Gateway + Lambda).

That said, we are also looking into supporting custom headers. That way, a user can pass any auth / security credentials they wish to.

**Comment by arliber** [comment]
Any news on that? any example of a workaround for getting AWS Elasticserach to work with dejavu?
Thanks

**Comment by siddharthlatest** [comment]
@arliber We support custom headers now. You can use them.

**Comment by arxpoetica** [comment]
@siddharthlatest do you have an example of what this would look like?

**Comment by geo909** [comment]
Apologies for resurrecting this, but could somebody briefly explain why we would now use custom headers to connect to an aws elasticsearch instance?
