### ISSUE TITLE
Filtering on nested data types

### ISSUE THREAD

**Issue by anfreita** [appbaseio/dejaVu#92]
@siddharthlatest you mentioned in #14 that filtering on nested data types is unsupported. I'm curious to know what the reason for this is. I've been experimenting with deja vu in the chrome extension and l love the utility and ease of use, but this is a pretty big limitation for us. Most of our documents are in the format:

```
{
  "id": "<uuid>",
  "name": "<human-readable-identifier>"
  "attributes": {
        <nested object of various attributes that differ pretty significantly across the index>
  }
}
```

Being able to filter on nested data types would be pretty huge, even if it requires a couple extra steps like adding them to the list of Displayed Attributes on the far right (gear icon).

- Andrew

**Comment by siddharthlatest** [comment]
@anfreita We now support writing a query for filtering UI views, this should be possible if you are using v1.0.0. You can write an ES query and the UI will be filtered based on the query.
