### ISSUE TITLE
Can't run application

### ISSUE THREAD

**Issue by maitredede** [appbaseio/dejaVu#93]
#### Tell us where you are using Dejavu (Hosted web app, Chrome extension, Docker Image, Within appbase.io)

Chrome extension and web app (chrome)

#### What is the version of Dejavu that you are using?

Current at date of message

#### Describe the issue that you are seeing, or the feature request :-), include any screenshots as necessary.

javascript error : Uncaught SyntaxError: Unexpected token ) at homePageHelper.js:691
blank screen

**Comment by siddharthlatest** [comment]
@MaitreDede The chrome web app is deprecated, the chrome extension is currently maintained. I do not see the issue that you are mentioning in the `1.0.0` version.

Can you go to the following URL chrome://extensions/?id=jopjeaiilkcibeohjdmejhoifenbnmlh and share a screenshot of what you see?

It should look something like this:

![](https://i.imgur.com/Tk2NSZp.png)

If you don't see the version to be 1.0.0, can you delete the extension and download it again from the chrome store?

**Comment by maitredede** [comment]
![image](https://user-images.githubusercontent.com/1765408/29341936-5d70a8dc-8273-11e7-89d8-0a5be13dc7c8.png)
![image](https://user-images.githubusercontent.com/1765408/29341948-726fcc0e-8273-11e7-8aa3-bb5694927b74.png)

**Comment by maitredede** [comment]
Error is in your sources : https://github.com/appbaseio/dejavu/blob/dev/live/src/js/helper/homePageHelper.js#L691

**Comment by siddharthlatest** [comment]
@MaitreDede Thanks, I am able to replicate the console error when toggling the Displayed Attributes columns, but this is not breaking any functionality for me. Is it the same for you?

**Comment by maitredede** [comment]
@siddharthlatest The application has never started for me.

**Comment by siddharthlatest** [comment]
@MaitreDede The new release fixes the uncaught syntax error.
