### ISSUE TITLE
Inline editing

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/dejaVu#94]
Adding an inline editing feature to DejaVu which would allow a user to edit the data more naturally:

- [x] Add support for boolean (via dropdown)
- [x] Add support for geo points
- [x] Add support for arrays (via a multidropdown list type component which shows different values and ability to add new values)
- [x] Add support for dates (elasticsearch formats https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html) (Try out for all different formats)
- [x] Add column labels showing data types
- [x] Validation of data (eg. adding string data in an integer field, show tooltip) (tooltips)
- [x] Error message when user does not has write credentials and edits
- [x] Geo point validation
- [x] Make a call on blur for date - time
- [x] Don't show time separately

More features
- [x] Determine mapping type (ES2, ES5 from url and accordingly apply to new columns)
- [x] A way to store edit state information in url for easy sharing

In branch https://github.com/appbaseio/dejavu/tree/inline-edit

**Comment by siddharthlatest** [comment]
@divyanshu013 seeing one issue with date fields 

![](https://i.imgur.com/607xc11.png)

Clicking on a field opens up an empty selectable input field. It requires a second click before the calendar view shows up.

![](https://i.imgur.com/gD7bXdC.png)
